### ISSUE TITLE
Helm Chart: Parallel podManagementPolicy causes pods not to join the cluster

### ISSUE THREAD

**Issue by JohnCMcDonough** [vernemq/docker-vernemq#100]
When deploying initially with three replicas and the podManagementPolicy set to Parallel, all three VMQ pods came up as separate clusters. It appears that if the initial vernemq-0 pod isn't up before the other pods, they never join the cluster. They also still report ready, so they will receive traffic from the service.

We probably need a to make sure that if you're not the vernemq-0 pod, and you haven't joined an existing cluster, we fail the health/readiness check.

**Comment by francois-travais** [comment]
Best would be not use parallel podManagementPolicy, that's it. It's a very common issue with cluster that one must start each member one by one.
