### ISSUE TITLE
Docker ENV vars are not replacing default vernemq config settings

### ISSUE THREAD

**Issue by nickm** [vernemq/docker-vernemq#107]
When I try to add something like:
        - name: DOCKER_VERNEMQ_LISTENER__WS__DEFAULT
          value: "0.0.0.0:9001"

The value appears to get prepended in the vernemq.conf file but does not replace the original default value. So my vernemq.conf ends up as:

########## Start ##########
listener.ws.default=0.0.0.0:9001
<< more configs >>
listener.ws.default = <local-ip>:8080
########## End ##########

Clearly the 8080 version is taking precendence and so my setting gets ignored.  This is not only for ws default but for other settings too (any that are in the vernemq config by default it would appear).

Thanks.

**Comment by dergraf** [comment]
@nickm thanks for opening the issue. 
The Docker image configures a predefined set of listeners, see https://github.com/vernemq/docker-vernemq/blob/master/bin/vernemq.sh#L80-L85

Those can't be overridden at the moment via environment variables, you'd need to mount your own `vernemq.conf.local` if you want to disable this.

If you want to add additional listeners you could do it by using a different listener name e.g. using
```
DOCKER_VERNEMQ_LISTENER__WS__MYWSLISTENER
or
DOCKER_VERNEMQ_LISTENER__TCP__MYTCPLISTENER
```
As you need to map the Docker ports properly you could keep the predefined listeners around (they won't harm) and only map the ports of the listeners that you really need.
