### ISSUE TITLE
Configuring custom listeners with dynamic addresses

### ISSUE THREAD

**Issue by bverhoeven** [vernemq/docker-vernemq#110]
I'm trying to enable a [WebSockets over SSL](https://vernemq.com/docs/configuration/websockets.html) listener using VerneMQ on Kubernetes (with multiple replicas, as per the Helm chart) and I'm running into issue.

It should be as simple as adding a new listener:

> listener.wss.default = ip:port

But, because of the way the docker image currently works, it's not that simple.

The listeners for `tcp`, `ws`, `vmq` and `http` are configured by the `vernemq.sh` startup script and this does work, but, as the other issues have also pointed out, there doesn't seem to be an easy way to add additional listeners while keeping the IP addresses dynamic.

I'm aware that there are similar issues - #48, #107, and probably others - that touch this subject in some ways, but the solutions given there unfortunately don't work for me. They seem to come down to either mounting a local configuration file, vernemq.conf.local, or to defining the listener through environment variables, in both cases with a known, static IP, or 0.0.0.0.

Unfortunately, neither of those will work in a dynamic environment, like Kubernetes, as each pod gets assigned a dynamic IP address on creation, and listening on 0.0.0.0 doesn't work if we want clustering.

Having thought of it some more, I'd like to propose a small addition to the `vernemq.conf.local` implementation: I think it would help if the startup script were to do an in-place substitution of a known string (for example, `{IP_ADDRESS}`) with the IP address of the host. 

A configuration like the one below would then work and could still be updated on startup, while respecting and not touching the other (custom) values:

```ini
...
listener.wss.default = {IP_ADDRESS}:8080 
...
```

I'd be happy to work this out and make a pull request if anyone feels this is something that you'd be interested in. I'd love to elaborate on the idea too in case there are doubts or questions.

**Comment by kllex** [comment]
I have a similar problem with clustering in kubernetes. I need to make a few changes to the standard `vernemq.conf` so I opted for the `vernemq.conf.local` way. Unfortunately there is no way to replace at least the IP-address of the `listener.vmq.clustering` which breaks clustering in kubernetes for me completely.

Like @bverhoeven above, I would suggest reusing an already used mechanism from the `vernemq.sh` and replace a predefined string via an `sed` command after the copy from `vernemq.conf.local` to `vernemq.conf`. 

I have submitted #142 for this. Please let me know if this suits your requirements or if it needs any refining or if this idea is totally beside the point ;) .

**Comment by larshesel** [comment]
I suppose we can close this as #142 was merged.

**Comment by Qanah** [comment]
I thank you very much if you add this lines it is simple use

```
if [ -z "$DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT" ]; then
   echo "listener.wss.default = ${IP_ADDRESS}:8080" >> /vernemq/etc/vernemq.conf
fi
```
