### ISSUE TITLE
Network Interfaces with numericals can break the IP_ADDRESS regex

### ISSUE THREAD

**Issue by JohnCMcDonough** [vernemq/docker-vernemq#124]
We were encountering issues when our interface name had numericals in it that were at least 7 characters long.
```
ip -4 addr show ${DOCKER_NET_INTERFACE:-eth0} | grep -oE '[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}'
1276567
10.x.x.x
```
```
ip -4 addr show eth0
3: eth0@if1276567: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default  link-netnsid 0
    inet 10.x.x.x/32 scope global eth0
       valid_lft forever preferred_lft forever

```

Our fix was to properly escape the dots in the regex so they match literal periods instead of any character.

**Comment by ioolkos** [comment]
Okay, thanks for the explanation and PR, @JohnCMcDonough!

**Comment by JohnCMcDonough** [comment]
Looks like the PR was merged. I guess we should close this issue?

**Comment by ioolkos** [comment]
:+1: thanks again
