### ISSUE TITLE
vernemq keeps crashing

### ISSUE THREAD

**Issue by valiksb** [vernemq/docker-vernemq#126]
0. helm install --name wfp-mqtt --namespace wfp vernemq/vernemq -f vernemq-values.xml
1. Kubernetes cluster v1.10.11-gke.1
2. helm client        v2.11.0+g2e55dbe
3. helm server        v2.12.2+g7d2b0c7
4. helm search vernemq
NAME           	CHART VERSION	APP VERSION	DESCRIPTION
vernemq/vernemq	1.2.0        	1.7.1-1    	VerneMQ is a high-performance, distributed MQTT message b...
5. the values.xml used
`additionalEnv:
  - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
    value: "on"`

5. kubectl logs --previous -p wfp-mqtt-vernemq-0

`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10443    0 10443    0     0   196k      0 --:--:-- --:--:-- --:--:--  192k
/usr/sbin/start_vernemq: line 29: warning: command substitution: ignored null byte in input
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10443    0 10443    0     0   309k      0 --:--:-- --:--:-- --:--:--  309k
config is OK
-config /vernemq/data/generated.configs/app.2019.03.29.14.22.23.config -args_file /vernemq/bin/../etc/vm.args -vm_args /vernemq/bin/../etc/vm.args
Exec:  /vernemq/bin/../erts-10.2.4/bin/erlexec -boot /vernemq/bin/../releases/1.7.1/vernemq               -config /vernemq/data/generated.configs/app.2019.03.29.14.22.23.config -args_file /vernemq/bin/../etc/vm.args -vm_args /vernemq/bin/../etc/vm.args              -pa /vernemq/bin/../lib/erlio-patches -- console -noshell -noinput
Root: /vernemq/bin/..
WARNING: This is a deprecated console configuration. Please use "[{level,info}]" instead.
=INFO REPORT==== 29-Mar-2019::14:22:25.112557 ===
    alarm_handler: {set,{system_memory_high_watermark,[]}}
14:22:25.130 [info] alarm_handler: {set,{system_memory_high_watermark,[]}}
14:22:25.218 [info] read state from file {[{[{actor,<<2,91,222,142,118,193,206,115,189,214,139,178,182,241,87,71,25,60,62,224>>}],1}],{dict,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[['VerneMQ@wfp-mqtt-vernemq-0.wfp-mqtt-vernemq-headless.wfp.svc.cluster.local',{[{actor,<<2,91,222,142,118,193,206,115,189,214,139,178,182,241,87,71,25,60,62,224>>}],1}]],[],[],[]}}},{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}
14:22:25.220 [info] writing state {[{[{actor,<<2,91,222,142,118,193,206,115,189,214,139,178,182,241,87,71,25,60,62,224>>}],1}],{dict,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[['VerneMQ@wfp-mqtt-vernemq-0.wfp-mqtt-vernemq-headless.wfp.svc.cluster.local',{[{actor,<<2,91,222,142,118,193,206,115,189,214,139,178,182,241,87,71,25,60,62,224>>}],1}]],[],[],[]}}},{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}} to disk <<75,2,131,80,0,0,1,48,120,1,203,96,206,97,96,96,96,204,96,130,82,41,12,172,137,201,37,249,69,185,64,81,17,166,232,123,125,101,7,207,21,239,189,214,189,105,219,199,112,119,73,27,187,7,89,137,140,89,25,156,41,12,44,41,153,201,37,137,140,137,2,64,200,145,24,144,104,144,33,144,133,6,50,24,81,197,192,86,128,8,166,20,6,175,176,212,162,188,84,223,64,135,242,180,2,221,220,194,146,18,221,50,144,64,110,161,174,129,30,134,80,70,106,98,74,78,106,113,49,72,70,175,184,44,89,47,57,167,180,184,36,181,72,47,39,63,57,49,135,52,183,131,220,136,112,63,3,41,238,7,105,5,0,249,62,103,4>>
14:22:25.238 [info] Datadir ./data/meta/meta/0 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,55287671}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.246 [info] Datadir ./data/meta/meta/1 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,57158377}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.251 [info] Datadir ./data/meta/meta/2 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,35443196}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.257 [info] Datadir ./data/meta/meta/3 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,55802224}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.263 [info] Datadir ./data/meta/meta/4 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,38734481}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.270 [info] Datadir ./data/meta/meta/5 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,48509146}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.277 [info] Datadir ./data/meta/meta/6 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,51975258}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.282 [info] Datadir ./data/meta/meta/7 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,47128230}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.289 [info] Datadir ./data/meta/meta/8 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,59344113}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.295 [info] Datadir ./data/meta/meta/9 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,33530218}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.302 [info] Datadir ./data/meta/meta/10 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,44334924}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.308 [info] Datadir ./data/meta/meta/11 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,37319887}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
14:22:25.379 [info] Try to start vmq_plumtree: ok
14:22:25.785 [info] loaded 0 subscriptions into vmq_reg_trie
14:22:25.795 [info] cluster event handler 'vmq_cluster' registered`

**Comment by Masticust** [comment]
Same issue. The pod is failing due to a failed liveness probe

`Normal   Killing  52s Killing container with id docker://vernemq:Container failed liveness probe.. Container will be killed and recreated.`

running vernemq ping on the pod using 
`k exec -it vernemq-0 -- bin/vernemq ping`
gives
```
=ERROR REPORT==== 1-Apr-2019::07:03:26.218288 ===
Failed to create cookie file '/vernemq/.erlang.cookie': eacces
=SUPERVISOR REPORT==== 1-Apr-2019::07:03:26.218523 ===
    supervisor: {local,net_sup}
    errorContext: start_error
    reason: {"Failed to create cookie file '/vernemq/.erlang.cookie': eacces",
             [{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},
              {auth,init,1,[{file,"auth.erl"},{line,140}]},
              {gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},
              {gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,undefined},
               {id,auth},
               {mfargs,{auth,start_link,[]}},
               {restart_type,permanent},
               {shutdown,2000},
               {child_type,worker}]
=CRASH REPORT==== 1-Apr-2019::07:03:26.218416 ===
  crasher:
    initial call: auth:init/1
    pid: <0.79.0>
    registered_name: []
    exception error: "Failed to create cookie file '/vernemq/.erlang.cookie': eacces"
      in function  auth:init_cookie/0 (auth.erl, line 286)
      in call from auth:init/1 (auth.erl, line 140)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [net_sup,kernel_sup,<0.46.0>]
    message_queue_len: 0
    messages: []
    links: [<0.77.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 2984
  neighbours:

escript: exception error: no match of right hand side value 
                 {error,
                     {{shutdown,
                          {failed_to_start_child,auth,
                              {"Failed to create cookie file '/vernemq/.erlang.cookie': eacces",
                               [{auth,init_cookie,0,
                                    [{file,"auth.erl"},{line,286}]},
                                {auth,init,1,[{file,"auth.erl"},{line,140}]},
                                {gen_server,init_it,2,
                                    [{file,"gen_server.erl"},{line,374}]},
                                {gen_server,init_it,6,
                                    [{file,"gen_server.erl"},{line,342}]},
                                {proc_lib,init_p_do_apply,3,
                                    [{file,"proc_lib.erl"},{line,249}]}]}}},
                      {child,undefined,net_sup_dynamic,
                          {erl_distribution,start_link,
                              [['VerneMQ_maint_561@vernemq-0.vernemq-headless.default.svc.cluster.local',
                                longnames],
                               false]},
                          permanent,1000,supervisor,
                          [erl_distribution]}}}
command terminated with exit code 127
```

**Comment by dergraf** [comment]
Thanks for the report. This should be fixed with the newest image tag `1.7.1-2`. Can you please verify? Thanks!

**Comment by valiksb** [comment]
I removed the vernemq from my helm repo and added it back again and then performed
`helm search vernemq
NAME           	CHART VERSION	APP VERSION	DESCRIPTION
vernemq/vernemq	1.2.0        	1.7.1-1    	VerneMQ is a high-performance, distributed MQTT message b...`

But it still keeps crashing

**Comment by Masticust** [comment]
@valiksb change the image tag in your values file from 1.7.1-**1** to 1.7.1-**2**.

@dergraf That solved the issue for me. Thanks for the fix!

**Comment by valiksb** [comment]
@Masticust thanks. @dergraf it works indeed

**Comment by ioolkos** [comment]
cool, thanks for effort and help
