### ISSUE TITLE
How to setup docker-vernemq with clusters?

### ISSUE THREAD

**Issue by samantond** [vernemq/docker-vernemq#129]
I'm running 2 docker containers with verneMQ
Container 1:
` docker run -d\
 -p 1883:1883\
 -p 8888:8888\
  -p 4369:4369\
 -p 44053:44053\
 -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" \
 -e "DOCKER_VERNEMQ_LISTENER.vmq.clustering=127.0.0.1:44053"\
 -e "DOCKER_VERNEMQ_NODENAME=172.17.0.2"\
 erlio/docker-vernemq`

Container 2:
` docker run -d\
 -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" 
 -e "DOCKER_VERNEMQ_DISCOVERY_NODE=172.17.0.2"
 -e "DOCKER_VERNEMQ_LISTENER.vmq.clustering=127.0.0.1:44053"
 -e "DOCKER_VERNEMQ_NODENAME=172.17.0.3"
 erlio/docker-vernemq
 `
after that I see 2 nodes in _/status_
![изображение](https://user-images.githubusercontent.com/8128598/55472013-c6221300-5613-11e9-90bb-0143788d2ce7.png)

But all clients always connect to the first node. I tried to set a limit for the max connections for this node via _listener.max_connections=20_ but when the limit is reached, then nothing happens . Clients don't connect to the second node (btw, the max clients for the first node is 29, and I can't understand why 9 is added  ).
And if I open vernemq.conf all parameters will remain in default values. I changed DOCKER_VERNEMQ_LISTENER.vmq.clustering to 127.0.0.1:44053 because I saw tips in this topic 
[https://github.com/vernemq/vernemq/issues/452](https://github.com/vernemq/vernemq/issues/452)

How it looks like with max_connections=10 
![изображение](https://user-images.githubusercontent.com/8128598/55475734-67619700-561d-11e9-983e-9cec5bd7f877.png)

**Comment by larshesel** [comment]
Since you only specifyed `-p 1883:1883` I assume you're connecting all clients to that port on the first node. If you want to connect to both nodes you'd need to expose the MQTT port on the other node as well and then connect to them - even better would be to put a load balancer (HAProxy, NGinx, ELB,...) in between which handles distribution strategies for you.
