### ISSUE TITLE
A docker container fails with permission error

### ISSUE THREAD

**Issue by manifest** [vernemq/docker-vernemq#134]
I'm trying to get around the [issue](https://github.com/vernemq/vernemq/issues/1101) that has already been fixed in the master branch. Since release isn't available yet, I've tried to build the docker image with the recent commit of the master branch, but without any success. I would appreciate any help or maybe information about the date of the next release if it has been already scheduled.

```bash
docker build --build-arg VERNEMQ_GIT_REF=master -t manifesthub/docker-vernemq:c57d37b-alpine -f Dockerfile.alpine .
docker run -ti --rm manifesthub/docker-vernemq:c57d37b-alpine
/vernemq/bin/vernemq: line 1: /vernemq/bin/../erts-10.3.5: Permission denied
Error generating config with cuttlefish
  run `vernemq config generate -l debug` for more information.
```

**Comment by dergraf** [comment]
Thanks for your patience. 1.8.0 is in the making, I will look at the Docker related issues when building the images for 1.8.0.

**Comment by manifest** [comment]
Thank you. I'm looking forward to it.

**Comment by manifest** [comment]
Oh, I see it's already there. I'll check it out. Thanks.

**Comment by foobarto** [comment]
I've run into this same issue with latest. Just wondering what was the fix? There doesn't seem to be anything wrong with the permissions :confused: 

```bash
$ docker run --rm -it vernemq bash
vernemq@58a99e88a701:~$ pwd
/vernemq
vernemq@58a99e88a701:~$ ls -al
total 40
drwxr-xr-x  1 vernemq vernemq 4096 Aug 27 11:26 .
drwxr-xr-x  1 root    root    4096 Aug 27 11:41 ..
drwxr-xr-x  2 vernemq vernemq 4096 Aug 27 11:25 bin
drwxr-xr-x  4 vernemq vernemq 4096 Aug 27 11:41 data
drwxr-xr-x  7 vernemq vernemq 4096 Aug 27 11:25 erts-10.4.4
drwxr-xr-x  2 vernemq vernemq 4096 Aug 27 11:41 etc
drwxr-xr-x 68 vernemq vernemq 4096 Aug 27 11:25 lib
drwxr-xr-x  3 vernemq vernemq 4096 Aug 27 11:41 log
drwxr-xr-x  3 vernemq vernemq 4096 Aug 27 11:25 releases
drwxr-xr-x  4 vernemq vernemq 4096 Aug 27 11:25 share
vernemq@58a99e88a701:~$ start_vernemq 
/vernemq/bin/vernemq: 1: /vernemq/bin/vernemq: /vernemq/bin/../erts-10.4.4: Permission denied
Error generating config with cuttlefish
  run `vernemq config generate -l debug` for more information.
vernemq@58a99e88a701:~$ 
```

**Comment by foobarto** [comment]
Ahh nevermind, I've messed up the contents of releases by accident.

**Comment by huckym** [comment]
I am building from source (rel 1.10.3) in a docker container and hitting this permission denied error. Any clues?

/home/vernemq # ls
bin          data         erts-10.4.1  etc          lib          log          releases     share

/home/vernemq # bin/vernemq start
bin/vernemq: line 172: /home/vernemq/bin/../erts-10.4.1: Permission denied
vmq_cluster_node_sup

**Comment by aurabhi** [comment]
I am trying run vernemq which is built from source. Checked out the master today. I see the same error.

../vernemq/bin/../erts-11.0: Permission denied
vmq_cluster_node_sup
vernemq failed to start within 15 seconds,
see the output of 'vernemq console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.
