### ISSUE TITLE
VerneMQ 1,9,0 still using OTP 21 as a build env

### ISSUE THREAD

**Issue by KirillSleta** [vernemq/docker-vernemq#153]
Hi!
Trying to include my plugin built via OTP 22 into the latest 1.9.0 release docker image (FROM erlio/docker-vernemq:1.9.0) and getting:
`10:03:39.113 [info] cluster event handler 'vmq_cluster' registered
10:03:44.830 [warning] can't load application plugin vmqkafka due to {unknown_module,vmqkafka}
Can't enable plugin: vmqkafka due to {unknown_module,vmqkafka}
10:03:44.830 [error] Loading of /vmqkafka/lib/vmqkafka/ebin/vmqkafka.beam failed: badfile
10:03:44.830 [error] beam/beam_load.c(1878): Error loading module vmqkafka:
  This BEAM file was compiled for a later version of the run-time system than 21.
  To fix this, please recompile this module with an 21 compiler.
  (Use of opcode 164; this emulator supports only up to 163.)`

According to the 1.9.0 release notes: 

> Make VerneMQ run on Erlang/OTP 22.

maybe changing [docker build environment ](https://github.com/vernemq/docker-vernemq/commit/7637bc9eec883fc07e2f4d007960fb89ab48bded#diff-3254677a7917c6c01f55212f86c57fbfL1)  to `FROM erlang:22 AS build-env` can solve the problem?

Thanks!

**Comment by larshesel** [comment]
VerneMQ is still built with OTP 21 and we're not yet ready to switch to OTP 22 - for that OTP 22 is too new. If you need OTP 22 you'll have to build VerneMQ yourself.

I hope this helps.
