### ISSUE TITLE
Helm 1.4.3 not working if replicaCount > 1

### ISSUE THREAD

**Issue by phenri00** [vernemq/docker-vernemq#162]
**Environment**

- Chart version: 1.4.3
- Docker: Docker desktop 2.1.02
- OS: MacOS Mojave
- ReplicaCount: 3

Also tested on a AWS EKS cluster 1.13

**Expected behavior**

Cluster with 3 pods running

**Actual behaviour**

One pod running fine with second pod falling with CrashLoopBackOff.

**Steps to reproduce the issue:**

helm install vernemq/vernemq --version 1.4.3 --set replicaCount=3

**Comment by larshesel** [comment]
This is due to a bug in the docker image scripts which was fixed a few days ago (see #159). You can work around it by running `helm install vernemq/vernemq --version 1.4.3 --set replicaCount=3 --set image.tag=latest`. I'll tag the docker image (1.9.2-1) and helm 1.4.4 later today.

**Comment by larshesel** [comment]
I just pushed it - the docker image have to be built but when the 1.9.2-1 image has been pushed to dockerhub the helm 1.4.4 version should hopefully be working.
