### ISSUE TITLE
Format of additionalEnv in helm chart

### ISSUE THREAD

**Issue by hengel2810** [vernemq/docker-vernemq#166]
I'm trying to install VerneMQ in my k8s cluster with helm (using terraform) and I want to set `DOCKER_VERNEMQ_ALLOW_ANONYMOUS` to `on`, but I had no luck with formatting the `additionalEnv` the right way. Can anyone help, please ?

```
resource "helm_release" "vernemq_cluster" {
    name = "vernemq-cluster"
    chart = "vernemq/vernemq"
    namespace = "http"
    set {
      name  = "replicaCount"
      value = 2
    }
    set {
      name  = "additionalEnv"
      value = "['DOCKER_VERNEMQ_ALLOW_ANONYMOUS': 'on']"
    }
    depends_on = [
      "kubernetes_cluster_role_binding.tiller",
      "kubernetes_service_account.tiller",
      "null_resource.voyager_secret"
    ]
}
```

**Comment by larshesel** [comment]
I'm afraid I don't have any idea how terraform works. You could try and ask in the vernemq #docker community channel. If you figure it out please drop a line here for future reference!

**Comment by larshesel** [comment]
Perhaps you can import the values.yaml like in this example: https://www.terraform.io/docs/providers/helm/release.html
