### ISSUE TITLE
Some messages not received at the time of subscription

### ISSUE THREAD

**Issue by tinto82** [vernemq/docker-vernemq#167]
Hello,
our production environment is made up of nodes running with Kubernetes on Google Cloud Platform. Over that is running an official docker image "erlio/docker-vernemq:1.8.0", in particular a cluster made up of 3 PODs.
Every POD has HAProxy in front of container Vernemq and have resources limits 0,5 cpu and 1,5 Gb RAM each one.
We currently have on average 12500 subscription in every moment, number that is constantly growing (on average around 500 more per month).
On average the use of resources is 40-50% of available RAM and 5% of the CPU available.
We found the following problem: when a device subscribes, despite the fact that ack subscription has been received, if a message from another client is published immediately on the topic sometimes it is lost. We verified that this happens when the client that publishes the message is connected to a different POD. It appears to be a problem of propagation of the subscription status within the cluster. We estimated that the propagation time at present is about 200 milliseconds, but it seems to be increasing. We are trying to carry out tests to have a more precise value.
We found the following information in your documentation:

> Due to the eventually consistent data model it is possible that during the Window of Uncertainty a publish won't take into account a subscription made on a remote node (in another partition). Obviously, VerneMQ can't deliver the message in this case. The same holds for delivering retained messages to remote subscribers.

(here: https://docs.vernemq.com/clustering/netsplits)

Is there a way to avoid this? Maybe a configuration. Have you ever estimated the duration of what you call "Window of Uncertainty"?
Thank you

**Comment by larshesel** [comment]
The window of uncertainty has nothing to do with the propagation time of subscriptions - that is simply the nature of eventually consistent data and this is the fundamental architectural design of making VerneMQ scale. The alternative is that for each subscription the operation would have to be atomic and the ack not sent to the client before the subscription has been sent to all nodes in the cluster. This would be very expensive and also mean that in case a node is down, no availability. So the current behaviour is usually not a problem as clients are anyway decoupled (the main idea behind MQTT) and also mostly also temporally. So having things which depends strictly on timing with VerneMQ is difficult.

We do have considered to make this possible (synchronized subscriptions) to configure for specific clients, but the idea has never made it further than the initial discussions.

I hope this helps
