### ISSUE TITLE
ARMv8 support ?

### ISSUE THREAD

**Issue by AntoinedeChassey** [vernemq/docker-vernemq#173]
Hey!
Are you guys planning to make a build for ARMv8 (ARM 64 bits) someday ?
Cheers,
Antoine

**Comment by dergraf** [comment]
Not sure if we're going to host pre-build images but we certainly want to streamline the process of creating a VerneMQ release that can be run on the ARM64 platforms.

**Comment by andreineculau** [comment]
FYI I have arm64 images here
https://github.com/ysoftwareab/docker-vernemq/pkgs/container/docker-vernemq

based on https://github.com/vernemq/vernemq/issues/1421#issuecomment-609467559

PS: I have only quickly tested the 1.10.3 (which I need), not the newer (1.12.3)
