### ISSUE TITLE
Vernemq Crashing after installing in K8

### ISSUE THREAD

**Issue by tanwarsatya** [vernemq/docker-vernemq#178]
Looks like some recent changes causing the crash due to not setting the accept_eula. Log shows following error -
```

Before you can continue, the product license
must be accepted. The license can be viewed at

    https://vernemq.com/end-user-license-agreement

If you do not accept this license you will
not be able to use VerneMQ.

Accepting the product license will modify the
VerneMQ config file

    /vernemq/bin/../etc/vernemq.conf

setting the "accept_eula" config to "yes".

Product license not accepted. Stopping.
```

**Comment by tanwarsatya** [comment]
updated the config value via environment variable.

```
additionalEnv:
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
    value: "yes"
```

**Comment by larshesel** [comment]
Hi @tanwarsatya yes, for commercial usage of the docker images you have to get in touch with the company behind VerneMQ. Please read our blog post about it: https://vernemq.com/blog/2019/11/26/vernemq-end-user-license-agreement.html

**Comment by medianatraaj** [comment]
Thanks a lot
