### ISSUE TITLE
Enabling stock Elixir plugin causes broker to stop responding to vmq-admin

### ISSUE THREAD

**Issue by damouse** [vernemq/docker-vernemq#179]
NOTE: I also created this ticket on the broker repo, but since it hasn't gotten attention (and I wasn't sure if this was an issue related to the docker configuration anyway) I'm reposting it here. 

I'm using a dockerized broker with a `vernemq.conf.local` and `###IPADDRESS###` placeholders. The plugin is the sample version of an elixier plugin provided [here](https://github.com/trarbr/vernemq_elixir_plugin) and has not been modified. A sample of this configuration can be found with instructions on reproducing [here](https://github.com/damouse/vernemq-issues) in 2-3 commands. 

In short, I'm building a broker with the unmodified elixir plugin and starting it in a docker container. I then `docker exec` into the container and run `vmq-admin`. When the elixir plugin is loaded, this fails. When it is not loaded, it succeeds. I have tried changing many of the existing configuration in vernemq.conf without success. It happens for me every time. 

Here is the top of the conf file being loaded when `vmq-admin` works:

```
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109

listener.tcp.default = ###IPADDRESS###:1883
listener.ws.default = ###IPADDRESS###:8080
listener.vmq.clustering = ###IPADDRESS###:44053
listener.http.metrics = ###IPADDRESS###:8888
listener.http.default = ###IPADDRESS###:8888

nodename = VerneMQ@###IPADDRESS###

# plugins.vernemq_elixir_plugin = on
# plugins.vernemq_elixir_plugin.path = /vernemq_elixir_plugin
```

It doesn't work when the last two lines are commented in. Occasional errors print even if vmq-admin is not run against it-- this prints every 30 seconds if the plugin is loaded:

```
23:27:58.182 [error] Error in process #PID<0.448.0> on node :"VerneMQ@172.17.0.2" with exit value:
{:function_clause, [{:dist_util, :convert_old_hsdata, [{:hs_data, #PID<0.60.0>, :undefined, :"VerneMQ@172.17.0.2", #Port<0.19>, #PID<0.449.0>, 0, [], :undefined, :undefined, :undefined, &:inet_tcp.send/2, &:inet_tcp.recv/3, #Function<0.56818488/1 in :inet_tcp_dist.do_accept/7>, #Function<1.56818488/1 in :inet_tcp_dist.do_accept/7>, #Function<2.56818488/1 in :inet_tcp_dist.do_accept/7>, #Function<3.56818488/2 in :inet_tcp_dist.do_accept/7>, #Function<4.56818488/1 in :inet_tcp_dist.do_accept/7>, &:inet_tcp_dist.getstat/1, :normal, &:inet_tcp_dist.setopts/2, &:inet_tcp_dist.getopts/2, :undefined, :undefined, :undefined, :undefined}], [file: 'dist_util.erl', line: 339]}, {:dist_util, :handshake_other_started, 1, [file: 'dist_util.erl', line: 149]}]}
```

Any ideas?

**Comment by larshesel** [comment]
Answered in the vernemq repo.
