### ISSUE TITLE
Support for Session Affinity option in service template of the Helm Chart

### ISSUE THREAD

**Issue by KedareshwarChaudhari** [vernemq/docker-vernemq#186]
I see that the [VMQ-Operator](https://github.com/vernemq/vmq-operator) has support for sessionAffinity field in the service yaml file. Is the same missing from the helm version or am I missing something here?

Example:
sessionAffinity: ClientIP

**Comment by ioolkos** [comment]
Merged PR https://github.com/vernemq/docker-vernemq/pull/194
