### ISSUE TITLE
Container fails to stop properly

### ISSUE THREAD

**Issue by KonstantinNosov** [vernemq/docker-vernemq#191]
`docker stop` kills container instead of shutting it down 

I'm using swarm and compose from readme.  On any action - container stop, stack rm or stack deploy, `docker container ls -a` shows `Exited (137)` in status.

docker info: 

```
Client:
 Debug Mode: false

Server:
 Containers: 30
  Running: 10
  Paused: 0
  Stopped: 20
 Images: 7
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: q6sxola9s316j2kj9qgzql29g
  Is Manager: true
  ClusterID: yjoowvjm6mq1405mh0un7wcqb
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.2
  Manager Addresses:
   192.168.65.2:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-161-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.953GiB
 Name: hostname
 ID: ZXQZ:TRPQ:SXIG:S5MO:LOGI:ZQJG:52WP:WIVT:DMWJ:74QE:ZMFQ:VCYP
 Docker Root Dir: /docker/data/data
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by KonstantinNosov** [comment]
looks like the problem is in leaving cluster in SIGTERM-handle

**Comment by dergraf** [comment]
I think the issue is exactly the same as mentioned here #192, but for Docker Swarm.
I think one could address the issue in the same PR.

**Comment by alexdesmet** [comment]
@KonstantinNosov could you attach a shell to one of the VerneMQ containers in your cluster and issue the 'vmq-admin cluster show' command? I'll try to provide a fix for both our issues.

**Comment by dergraf** [comment]
@alexdesmet I'd also look at the start shell script and grep for `SWARM` so you see how the nodename gets constructed in the case of Docker Swarm

**Comment by KonstantinNosov** [comment]
I've already patched  vernemq.sh from my Dockefile to fixed it 

the root of the problem is [here](https://github.com/vernemq/docker-vernemq/blob/master/bin/vernemq.sh#L144) 
```
# Start VerneMQ
/vernemq/bin/vernemq console -noshell -noinput $@
pid=$(ps aux | grep '[b]eam.smp' | awk '{print $2}')
wait $pid
```
`/vernemq/bin/vernemq console -noshell -noinput ` never exits so pid is not stored 

And another problem is here [here](https://github.com/vernemq/docker-vernemq/blob/master/bin/vernemq.sh#L134)
```
# SIGTERM-handler
sigterm_handler() {
    if [ $pid -ne 0 ]; then
        # this will stop the VerneMQ process
        /vernemq/bin/vmq-admin cluster leave node=VerneMQ@$IP_ADDRESS -k > /dev/null
        wait "$pid"
    fi
    exit 143; # 128 + 15 -- SIGTERM
}
```
if DOCKER_VERNEMQ_NODENAME var is provided `VerneMQ@$IP_ADDRESS ` is wrong nodename
it should rather be 
```
        # this will stop the VerneMQ process
        /vernemq/bin/vmq-admin cluster leave node=VerneMQ@${DOCKER_VERNEMQ_NODENAME:-${IP_ADDRESS}} -k > /dev/null
```

**Comment by xabinapal** [comment]
I've submitted a PR (#208) that fixes this issue. The problem is that VerneMQ is started as a foreground process, and keeps busy the parent shell process, which can't handle the signals received (trapped signals can not be handled is another process is running). Solution involves executing VerneMQ on the background and waiting for it to finish (`wait` command allow trap handlers to execute).
