### ISSUE TITLE
Kubernetes cluster leave not triggering

### ISSUE THREAD

**Issue by alexdesmet** [vernemq/docker-vernemq#192]
Hi,

I am trying to build a VerneMQ cluster that auto-scales on GKE. Scaling up works like a charm and the new nodes are added to the cluster. When downscaling, the node doesn't leave the cluster before the container is exited. I believe this piece is responsible from [bin/vernemq.sh](https://github.com/vernemq/docker-vernemq/blob/master/bin/vernemq.sh):

```bash
# SIGTERM-handler
sigterm_handler() {
    if [ $pid -ne 0 ]; then
        # this will stop the VerneMQ process
        /vernemq/bin/vmq-admin cluster leave node=VerneMQ@$IP_ADDRESS -k > /dev/null
        wait "$pid"
    fi
    exit 143; # 128 + 15 -- SIGTERM
}
```

When using the DOCKER_VERNEMQ_DISCOVERY_KUBERNETES env variable, the node name changes to VerneMQ@pod-name.namespace.svc.clustername

Suggested fix:
```bash
# SIGTERM-handler
sigterm_handler() {
    if [ $pid -ne 0 ]; then
        # this will stop the VerneMQ process
        if [ ! -z $VERNEMQ_KUBERNETES_HOSTNAME ]; then
            /vernemq/bin/vmq-admin cluster leave node=$VERNEMQ_KUBERNETES_HOSTNAME-k > /dev/null
        else
            /vernemq/bin/vmq-admin cluster leave node=VerneMQ@$IP_ADDRESS -k > /dev/null
        fi
        wait "$pid"
    fi
    exit 143; # 128 + 15 -- SIGTERM
}
```

The current flow is that I manually enter the leave command before downscaling. That way the connected client sessions are rerouted to the other nodes before the containers exits. Thanks for looking in to this.

**Comment by ioolkos** [comment]
@alexdesmet thanks.. is the issue that the VerneMQ leave takes too long, or is the issue a nodename issue?
The snippet you provided fixes it for you?

**Comment by alexdesmet** [comment]
@ioolkos I haven't edited the script itself inside the container as it is write protected. I do have observed the following:

When executing the cluster leave command by using the IP address of the container, the leave command outputs "done". But the node is still a part of the cluster.

```bash
vernemq@vernemq-1:~$ vmq-admin cluster leave node=VerneMQ@10.44.2.13 -k
Done
vernemq@vernemq-1:~$ vmq-admin cluster show
+-----------------------------------------------------------+-------+
|                           Node                            |Running|
+-----------------------------------------------------------+-------+
|VerneMQ@vernemq-1.vernemq.ingress-staging.svc.cluster.local| true  |
|VerneMQ@vernemq-0.vernemq.ingress-staging.svc.cluster.local| true  |
+-----------------------------------------------------------+-------+
```

When entering the command with the full nodename, everything goes as aspected:

```bash
vernemq@vernemq-1:~$ vmq-admin cluster leave node=VerneMQ@vernemq-1.vernemq.ingress-staging.svc.cluster.local -k
Migrated 0/0 queues and 0/0 messages
Done
```

On the other node:
```bash
vernemq@vernemq-0:/usr/sbin$ vmq-admin cluster show
+-----------------------------------------------------------+-------+
|                           Node                            |Running|
+-----------------------------------------------------------+-------+
|VerneMQ@vernemq-0.vernemq.ingress-staging.svc.cluster.local| true  |
+-----------------------------------------------------------+-------+
```

I could solve this myself by providing [a preStop script](https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/) in the container yaml but I feel it could be solved cleaner and more generic for all clusters using nodenames in stead of IP addresses.

**Comment by alexdesmet** [comment]
I have implemented this workaround for the time being

```
lifecycle:
    preStop:
        exec:
            command:
              - /bin/sh
              - -c
              - /vernemq/bin/vmq-admin cluster leave node=VerneMQ@${MY_POD_NAME}.vernemq.${DOCKER_VERNEMQ_KUBERNETES_NAMESPACE}.svc.cluster.local -k;sleep 5
```

**Comment by dergraf** [comment]
@alexdesmet your addition in the sigterm handler is correct. Happy to review a PR.

**Comment by alexdesmet** [comment]
I'll go ahead and close this issue. Thanks for the merge!
