### ISSUE TITLE
Cannot install chart / failed to pull image 1.10.3-alpine

### ISSUE THREAD

**Issue by AndrewBedscastle** [vernemq/docker-vernemq#217]
I did

1. helm repo add vernemq https://vernemq.github.io/docker-vernemq
2. helm repo update
3. helm install vernemq/vernemq

And I always end up: 

Failed to pull image "vernemq/vernemq:1.10.3-alpine": rpc error: code = Unknown desc = Error response from daemon: manifest for vernemq/vernemq:1.10.3-alpine not found: manifest unknown: manifest unknown

What information can I provide to debug the issue?

**Comment by codeadict** [comment]
There seems to be an issue with the CI release, the tag `latest` was created in Docker Hub but not the specific versions for `1.10.3`, trying to find why and how to fix it.

**Comment by codeadict** [comment]
@AndrewBedscastle you should be fine now. Thanks for reporting!
