### ISSUE TITLE
When will the new version of Helm be released？

### ISSUE THREAD

**Issue by An0nymous0** [vernemq/docker-vernemq#229]

**Comment by ioolkos** [comment]
@An0nymous0 released it under tag 1.6.5

**Comment by An0nymous0** [comment]
@ioolkos 
Thank you
But i found helm charts repository not upgrade
![image](https://user-images.githubusercontent.com/6836030/89980026-96712980-dca3-11ea-9aca-0957331603c5.png)

**Comment by ioolkos** [comment]
@An0nymous0 my apologies, you are right... but now I'm confused. Did this work in the past? is it a documentation error?
I'll clear it up as soon as I find a moment.

**Comment by ioolkos** [comment]
@An0nymous0 seems like the travisbot build the correct helm-version. Can you show what steps you are doing?

**Comment by An0nymous0** [comment]
@ioolkos 
After executing helm repo update, you will go to https://vernemq.github.io/docker-vernemq to update, all versions are recorded in it, and the corresponding page should be https://github.com/vernemq/docker-vernemq/blob/gh -pages/index.yaml, but now it seems that this address is 404, below is my helm repo configuration
![image](https://user-images.githubusercontent.com/6836030/90123888-18d81700-dd92-11ea-904f-e2dc3ecec571.png)
---
This is the repo address of another application for reference: https://repos.emqx.io/charts

I know how helm is updated, but I don’t know how our update address is constructed

**Comment by ioolkos** [comment]
@An0nymous0 seems I was finally able to fix this, so we can build helm charts again in the future (and there should be a current chart)

**Comment by An0nymous0** [comment]
Has been successfully upgraded with helm
thanks!
