### ISSUE TITLE
Travis build doesn't build helm-1.6.5

### ISSUE THREAD

**Issue by ioolkos** [vernemq/docker-vernemq#235]
If you use `helm install`, currently you'll land on release helm-1.6.3 (VerneMQ Release 1.10.3), instead of the latest Verne release.

I have looked into this but currently no clue why the Travisbot does not update the gh-pages branch:
https://github.com/vernemq/docker-vernemq/tree/gh-pages
Travis seems to log that it does update the build.

cc @francois-travais @codeadict maybe this rings a bell to you?

**Comment by ioolkos** [comment]
This is what the Travis `after_script` does, looks as usual. But it seems nothing is pushed to Github.

```$ git config user.name "travis"
after_script.2

0.00s$ git config user.email "deploy@travis-ci.org"
after_script.3

0.07s$ git stash push -u -- vernemq-*.tgz

Saved working directory and index state WIP on (no branch): 9ca9db2 Merge pull request #234 from ioolkos/rel_1.10.4.1
after_script.4

0.00s$ git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
after_script.5

0.91s$ git fetch origin gh-pages

From https://github.com/vernemq/docker-vernemq

 * branch            gh-pages   -> FETCH_HEAD

 * [new branch]      gh-pages   -> origin/gh-pages
after_script.6

0.01s$ git checkout gh-pages

Previous HEAD position was 9ca9db2 Merge pull request #234 from ioolkos/rel_1.10.4.1

Switched to a new branch 'gh-pages'

Branch 'gh-pages' set up to track remote branch 'gh-pages' from 'origin'.
after_script.7

0.05s$ git stash pop

Already up to date!

On branch gh-pages

Your branch is up to date with 'origin/gh-pages'.

Untracked files:

  (use "git add <file>..." to include in what will be committed)

	vernemq-1.6.5.tgz

nothing added to commit but untracked files present (use "git add" to track)

Dropped refs/stash@{0} (a6d05106cbbd4717d52b8de874c5d8045fce0664)
after_script.8

0.06s$ helm repo index . --url https://vernemq.github.io/docker-vernemq
after_script.9

0.01s$ git add vernemq-*.tgz index.yaml
after_script.10

0.01s$ git commit -m "Add helm chart release $TRAVIS_BRANCH"

[gh-pages 449df78] Add helm chart release helm-1.6.5-1

 2 files changed, 26 insertions(+), 16 deletions(-)

 create mode 100644 vernemq-1.6.5.tgz
after_script.11

0.34s$ git push -q https://$GITHUB_USER:$GITHUB_TOKEN@github.com/vernemq/docker-vernemq gh-pages &>/dev/null

Done. Your build exited with 0.
```

**Comment by mstavrev** [comment]
Can you try removing the '&>/dev/null' at the end of:

git push -q https://$GITHUB_USER:$GITHUB_TOKEN@github.com/vernemq/docker-vernemq gh-pages &>/dev/null

Most likely something fails on pushing the changed onto the gh-pages branch, which hosts the helm repo files. The output may be helpful to identify the reason.

**Comment by ioolkos** [comment]
@mstavrev oh, thanks, that might be a good idea! will try this.

Seems strange that I'd see no error on github side. Or maybe that be swallowed by /dev/null too.

**Comment by ioolkos** [comment]
@mstarev the error is this:
```
$ git push -q https://$GITHUB_USER:$GITHUB_TOKEN@github.com/vernemq/docker-vernemq gh-pages

remote: You must verify your email address.

remote: See https://github.com/settings/emails.

fatal: unable to access 'https://[secure]:[secure]@github.com/vernemq/docker-vernemq/': The requested URL returned error: 403
```

I had a secondary e-mail adress not verified in my profile, but after fixing that still getting the above error.

**Comment by ioolkos** [comment]
Lol, this is driving me crazy. `docker-vernemq` was the only repo not migrated from travis.org to travis.com. So I did that. Then I created a new access token, and stored that in repo settings on Travis. Still doesn't work.

**Comment by mstavrev** [comment]
Unfortunately, I am completely new to travis-ci and how it integrates with GitHub. 

Out of curiosity I had signed up on travis-ci.com with my GitHub account and I see it offers me to integrate with either all or just specific subset of my projects. I choose one specific and I see it (on GitHub/Personal Settings/Applications) it integrated under "Installed GitHub Apps" and also "Authorized OAuth Apps". I guess your way of integrating is a different one.

**Comment by mstavrev** [comment]
I see there is native support on Travis for uploading (pushing) to gh-pages - https://docs.travis-ci.com/user/deployment/pages/ .

**Comment by ioolkos** [comment]
Jep, that's exactly what I'm doing. I think it's an auth issue, but I can't figure out why. Maybe there's some token caching somewhere (Github or Travis).

**Comment by ioolkos** [comment]
Seems I was able to fix this. I deleted and created new access tokens multiple times. Copy/paste errors? cache issues? 
We'll never know.
