### ISSUE TITLE
can't call function auth_on_register with args

### ISSUE THREAD

**Issue by netgsm** [vernemq/docker-vernemq#247]
hi, 
I am trying to install vernemq on postgresql and docker swarm. I get the following error.

10:34:22.246 [error] can't call function auth_on_register with args [{addr,<<"10.0.0.2">>},{port,57950},{mountpoint,<<>>},{client_id,<<"cxxx">>},{username,<<"xxx-bridge">>},{password,<<"xxxx">>},{clean_session,true}] in "./share/lua/auth/postgres.lua" due to {badarg,'#',[false]}

10:34:22.247 [warning] can't authenticate client {[],<<"chirpstack-gateway">>} from 10.0.0.2:57950 due to lua_script_error

vmq0:
    image: vernemq/vernemq
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
    networks:
      - vmq_net
    command: >
      /bin/sh -c "cp /usr/sbin/start_vernemq /vernemq/etc/start_vernemq &&
      sed -i 's/listener.tcp.default.*:1883/listener.tcp.default = 0.0.0.0:1883/g' /vernemq/etc/start_vernemq &&
      sed -i 's/listener.ws.default.*:8080/listener.ws.default = 0.0.0.0:8080/g' /vernemq/etc/start_vernemq &&
      sed -i 's/listener.http.metrics.*:8888/listener.http.metrics = 0.0.0.0:8888/g' /vernemq/etc/start_vernemq &&
      chmod +x /vernemq/etc/start_vernemq &&
      /vernemq/etc/start_vernemq &&
      rm -rf /vernemq/etc/start_vernemq"
  vmq:
    image: vernemq/vernemq
    ports:
        - 1885:1883
        - 18888:8888
    depends_on:
      - vmq0
    networks:
      - vmq_net
    command: >
      /bin/sh -c "cp /usr/sbin/start_vernemq /vernemq/etc/start_vernemq &&
      sed -i 's/listener.tcp.default.*:1883/listener.tcp.default = 0.0.0.0:1883/g' /vernemq/etc/start_vernemq &&
      sed -i 's/listener.ws.default.*:8080/listener.ws.default = 0.0.0.0:8080/g' /vernemq/etc/start_vernemq &&
      sed -i 's/listener.http.metrics.*:8888/listener.http.metrics = 0.0.0.0:8888/g' /vernemq/etc/start_vernemq &&
      chmod +x /vernemq/etc/start_vernemq &&
      /vernemq/etc/start_vernemq &&
      rm -rf /vernemq/etc/start_vernemq"
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_DISCOVERY_NODE: vmq0
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_POSTGRES__ENABLED: "on"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__HOST: xxxxx
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PORT: xxxx
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__USER: "xx"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD: "xxx"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__DATABASE: "xxx"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD_HASH_METHOD: "crypt"
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: "on"
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "off"
    deploy:
      replicas: 2

**Comment by ioolkos** [comment]
@netgsm hm... have you added ACLs for that subscriber? 
https://docs.vernemq.com/configuration/db-auth#postgresql

**Comment by netgsm** [comment]
yes ,
I added in database and extansion
CREATE EXTENSION pgcrypto;
CREATE TABLE vmq_auth_acl
 (
   mountpoint character varying(10) NOT NULL,
   client_id character varying(128) NOT NULL,
   username character varying(128) NOT NULL,
   password character varying(128),
   publish_acl json,
   subscribe_acl json,
   CONSTRAINT vmq_auth_acl_primary_key PRIMARY KEY (mountpoint, client_id, username)
 );
