### ISSUE TITLE
How to setup TLS? 

### ISSUE THREAD

**Issue by cedricve** [vernemq/docker-vernemq#256]
Is there any documentation how to setup the SSL certificates? And mount them into a K8S secret?
https://github.com/vernemq/docker-vernemq/blob/master/helm/vernemq/values.yaml#L160

Any help would be helpful ;)

**Comment by cedricve** [comment]
found documentation in helm chart, but is outdated!

**Comment by ioolkos** [comment]
@cedricve thanks, can you let me know where it's outdated, or fix it?

**Comment by cedricve** [comment]
https://github.com/vernemq/docker-vernemq/tree/master/helm/vernemq

I will send a PR after I fixed my issue https://github.com/vernemq/docker-vernemq/issues/171
