### ISSUE TITLE
listener.wss.default missing

### ISSUE THREAD

**Issue by cedricve** [vernemq/docker-vernemq#257]
I'm trying to enable secure websockets but when enabling it in here 
https://github.com/vernemq/docker-vernemq/issues/171 -> it doesnt do anything. It exposes the services, but doesnt update the vernemq.conf 

cat /etc/vernemq/vernemq.conf 

########## Start ##########
accept_eula=yes
listener.ssl.default=10.24.0.18:8883
listener.ssl.keyfile=/etc/ssl/vernemq/tls.key
allow_subscribe_during_netsplit=on
listener.ssl.certfile=/etc/ssl/vernemq/tls.crt
allow_publish_during_netsplit=on
allow_anonymous=on
listener.ssl.cafile=/etc/ssl/vernemq/tls.crt
allow_unsubscribe_during_netsplit=on
log.console=console
allow_register_during_netsplit=on
listener.tcp.localhost=127.0.0.1:1883
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.24.0.18:1883
listener.ws.default = 10.24.0.18:8080
listener.vmq.clustering = 10.24.0.18:44053
listener.http.metrics = 10.24.0.18:8888
########## End ##########

**Comment by ioolkos** [comment]
Wait.. is this missing here? 
https://github.com/vernemq/docker-vernemq/blob/3281d3e11395d803d7dcf0978c69682a8b656624/bin/vernemq.sh#L118

**Comment by cedricve** [comment]
yes it's missing for the WSS part good find ;)

**Comment by ioolkos** [comment]
Seems like it. Should all be the same story, but I often get confused what's for Docker, for Helm, for Kubernetes.
Thanks!

**Comment by cedricve** [comment]
hehe, cool 😎 let me know if i need to test something

**Comment by cedricve** [comment]
fixed by https://github.com/vernemq/docker-vernemq/pull/258/files special thanks @ioolkos  ;)
