### ISSUE TITLE
Vernemq on openshift 3.9

### ISSUE THREAD

**Issue by boks21** [vernemq/docker-vernemq#269]
I can build a VerneMQ image and run locally on Docker, using oficial Docker File.
When i push it openshift and deploy it on openshift, POD as problem, vm.args is not found.

What kind of permissions need i change on DockerFile?

Thanks

**Comment by ioolkos** [comment]
@boks21 I'm not sure how I can help. Does this (still open, old) PR ring a bell to you? https://github.com/vernemq/docker-vernemq/pull/131

**Comment by boks21** [comment]
@ioolkos  yes, it rangs. I did some changes to Dockerfile and now it works. I will stay tuned with your new changes. Thanks a lot

**Comment by ioolkos** [comment]
@boks21 great can you let us know what the issue was and what worked for you?

**Comment by boks21** [comment]
Sure, my problem was about Openshift changed group of etc, data and log from /vernemq and got a error when ran it.

Then changed my DockerFile to following and problems are gone, now i can run it.

`
FROM alpine:3.9

WORKDIR /vernemq
ENV INSTALL_DIR /vernemq

ENV DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR="app=vernemq"
ENV DOCKER_VERNEMQ_LOG__CONSOLE=console
ENV PATH="/vernemq/bin:$PATH"
ENV VERNEMQ_VERSION="1.11.0"
ENV DOCKER_VERNEMQ_ACCEPT_EULA=yes

RUN mkdir -p $INSTALL_DIR && \
	apk --no-cache --update --available upgrade && \
    apk add --no-cache ncurses-libs openssl libstdc++ jq curl bash snappy-dev 

COPY  bin/vernemq.sh /usr/sbin/start_vernemq

RUN curl -L https://github.com/vernemq/vernemq/releases/download/$VERNEMQ_VERSION/vernemq-$VERNEMQ_VERSION.alpine.tar.gz -o /tmp/vernemq-$VERNEMQ_VERSION.alpine.tar.gz && \
    tar -xzvf /tmp/vernemq-$VERNEMQ_VERSION.alpine.tar.gz && \
    rm /tmp/vernemq-$VERNEMQ_VERSION.alpine.tar.gz && \
    ln -s /vernemq/etc /etc/vernemq && \
    ln -s /vernemq/data /var/lib/vernemq && \
    ln -s /vernemq/log /var/log/vernemq
 
COPY  files/vm.args /vernemq/etc/vm.args  

# Ports
# 1883  MQTT
# 8883  MQTT/SSL
# 8080  MQTT WebSockets
# 44053 VerneMQ Message Distribution
# 4369  EPMD - Erlang Port Mapper Daemon
# 8888  Prometheus Metrics
# 9100 9101 9102 9103 9104 9105 9106 9107 9108 9109  Specific Distributed Erlang Port Range

EXPOSE 1883 8883 8080 44053 4369 8888 9100 9101 9102 9103 9104 9105 9106 9107 9108 9109

HEALTHCHECK CMD vernemq ping | grep -q pong

RUN chgrp -R 0 /vernemq && \
    chmod -R g=u /vernemq

CMD ["start_vernemq"]
`
