### ISSUE TITLE
SSL listener not working

### ISSUE THREAD

**Issue by isidnis** [vernemq/docker-vernemq#272]
I am trying to setup a vernemq broker with tls enabled. I have tried to use my own selfsigned certificates with no success (even though I have already used them in rabbitmq deployments). So I have tried to setup the deployment with the provided example certs with no success either. I use the following values.yml

values.yml

secretMounts:
  - name: vernemqss
    secretName: vernemqss
    path: /etc/ssl/vernemq

additionalEnv:
  - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ACCEPT_EULA
    value: "yes"
  - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__CAFILE
    value: "/etc/ssl/vernemq/ca.crt"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE
    value: "/etc/ssl/vernemq/tls.crt"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE
    value: "/etc/ssl/vernemq/tls.key"
  - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
    value: "on"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE
    value: "off"
  - name: DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL
    value: "debug"
  - name: DOCKER_VERNEMQ_LOG__CONSOLE
    value: "both"

I create the secrets with

apiVersion: v1
kind: Secret
metadata:
  name: vernemqss
  namespace: default
type: kubernetes.io/tls
data:
  ca.crt: |
    Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgICAgICBTZXJpYWwgTnVtYmVyOiAxICgweDEpCiAgICBTaWduYXR1cmUgQWxnb3JpdGhtOiBzaGEyNTZXaXRoUlNBRW5jcnlwdGlvbgogICAgICAgIElzc3VlcjogQz1DSCwgU1Q9QmFzZWwtVG93biwgTD1CYXNlbCwgTz1FcmxpbyBNUVRUIFByb2plY3QsIE9VPVRlc3RpbmcsIENOPVJvb3QgQ0EKICAgICAgICBWYWxpZGl0eQogICAgICAgICAgICBOb3QgQmVmb3JlOiBTZXAgMjUgMjA6NTA6NTkgMjAxNCBHTVQKICAgICAgICAgICAgTm90IEFmdGVyIDogU2VwIDI0IDIwOjUwOjU5IDIwMTkgR01UCiAgICAgICAgU3ViamVjdDogQz1DSCwgU1Q9QmFzZWwtVG93biwgTz1FcmxpbyBNUVRUIFByb2plY3QsIE9VPVRlc3RpbmcsIENOPVNpZ25pbmcgQ0EKICAgICAgICBTdWJqZWN0IFB1YmxpYyBLZXkgSW5mbzoKICAgICAgICAgICAgUHVibGljIEtleSBBbGdvcml0aG06IHJzYUVuY3J5cHRpb24KICAgICAgICAgICAgICAgIFB1YmxpYy1LZXk6ICgxMDI0IGJpdCkKICAgICAgICAgICAgICAgIE1vZHVsdXM6CiAgICAgICAgICAgICAgICAgICAgMDA6ZDE6YzY6ODM6Y2E6MmY6NmE6Njc6Mzk6YTg6Zjk6MWY6Y2M6MzA6NzY6CiAgICAgICAgICAgICAgICAgICAgMzM6Zjc6NGM6NTQ6N2Q6MjM6MTc6YjY6NWU6ZjA6NTY6M2M6NTQ6Nzc6OWE6CiAgICAgICAgICAgICAgICAgICAgNDE6NjU6MjM6ZGE6MzI6OGI6YzE6ZWQ6YzQ6YzI6YTI6YzI6ZDM6Y2I6ZGQ6CiAgICAgICAgICAgICAgICAgICAgNDc6ZWE6M2Y6MjM6ZDU6ZjM6M2I6N2E6OTk6MTQ6MWY6MmU6M2M6ZjQ6NDA6CiAgICAgICAgICAgICAgICAgICAgNTA6Njk6ZGE6YTg6NDg6N2E6ODE6YmY6ZTU6MmY6MzU6Njk6NGM6OWY6MzI6CiAgICAgICAgICAgICAgICAgICAgZmQ6NGU6OGI6Mjc6YjY6NTU6OTA6MjE6NTQ6ZmI6ZDk6Mzk6MzY6MDE6NWY6CiAgICAgICAgICAgICAgICAgICAgMTA6NmM6Yzk6ZDI6OWE6MDY6MGI6NDQ6ZTY6M2U6Mzc6YWQ6YjI6ODk6MjQ6CiAgICAgICAgICAgICAgICAgICAgMDQ6Zjg6YmE6ZGE6NTY6Yzc6NWU6OTM6NmE6N2I6ZjY6MzE6MjQ6MmI6Njg6CiAgICAgICAgICAgICAgICAgICAgY2Q6Yjc6NTk6ZGI6ZTQ6NDU6YTc6NmU6OTkKICAgICAgICAgICAgICAgIEV4cG9uZW50OiA2NTUzNyAoMHgxMDAwMSkKICAgICAgICBYNTA5djMgZXh0ZW5zaW9uczoKICAgICAgICAgICAgWDUwOXYzIFN1YmplY3QgS2V5IElkZW50aWZpZXI6IAogICAgICAgICAgICAgICAgMjk6M0Q6NDQ6MTY6Q0Y6MzM6MzM6Q0Q6MkQ6NjA6REY6NEQ6QTc6MTc6RDA6MEI6RDQ6RTE6MjM6QzAKICAgICAgICAgICAgWDUwOXYzIEF1dGhvcml0eSBLZXkgSWRlbnRpZmllcjogCiAgICAgICAgICAgICAgICBrZXlpZDo0RjpGRDpDMTo1RjowOTpDNDpBNzpBNjpERjpGRjo5ODo5NTpBODozMDozMzowMDo0MTozRDo0NTo3QgoKICAgICAgICAgICAgWDUwOXYzIEJhc2ljIENvbnN0cmFpbnRzOiAKICAgICAgICAgICAgICAgIENBOlRSVUUKICAgIFNpZ25hdHVyZSBBbGdvcml0aG06IHNoYTI1NldpdGhSU0FFbmNyeXB0aW9uCiAgICAgICAgIGEwOmViOmI4OmQ4OjlkOjYwOjQ2OmI4OjJlOjM4OmY2OmY2OjE1OjczOmZlOjY5OmUwOmIzOgogICAgICAgICAxMTpjYzpiZTpiYjpkMzo0ODozMDpjOTo0NTpmYTo5Nzo5MzpjNTo1ZTplZDowYTowZTo1ZjoKICAgICAgICAgYWM6MDk6YzE6ZDk6ZGI6Yjg6MDk6MTY6NzY6YTA6N2M6YzY6MjI6ZGI6OTQ6ZmQ6NDA6OTA6CiAgICAgICAgIDM2OmFjOjYyOjk4Ojc4OjJlOmY2OjExOjg0OjQ4OmY3OmU1OjdhOjBmOmIzOjQxOmU3OmU1OgogICAgICAgICBlZDplMDplODo2NDozOTphOTo1Mzo4ODphZjoxODpjNzoxYjoxMjowNzoyYToxNjo4ODpjOToKICAgICAgICAgMTY6ZTI6Mjg6NGY6YzI6NjE6MTg6ZDA6OTE6NTQ6Yjc6NDk6OGM6NWE6MWQ6OTY6YTc6ZGU6CiAgICAgICAgIDQ3Ojc3OjhmOmExOjQ2OjBlOmI3OmMxOjFmOmY1OjMyOmRkOjY3OmUyOjg5OmE1OjI1OmUxOgogICAgICAgICA4ZTo3OQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ256Q0NBZ2lnQXdJQkFnSUJBVEFOQmdrcWhraUc5dzBCQVFzRkFEQnpNUXN3Q1FZRFZRUUdFd0pEU0RFVApNQkVHQTFVRUNBd0tRbUZ6Wld3dFZHOTNiakVPTUF3R0ExVUVCd3dGUW1GelpXd3hHekFaQmdOVkJBb01Fa1Z5CmJHbHZJRTFSVkZRZ1VISnZhbVZqZERFUU1BNEdBMVVFQ3d3SFZHVnpkR2x1WnpFUU1BNEdBMVVFQXd3SFVtOXYKZENCRFFUQWVGdzB4TkRBNU1qVXlNRFV3TlRsYUZ3MHhPVEE1TWpReU1EVXdOVGxhTUdZeEN6QUpCZ05WQkFZVApBa05JTVJNd0VRWURWUVFJREFwQ1lYTmxiQzFVYjNkdU1Sc3dHUVlEVlFRS0RCSkZjbXhwYnlCTlVWUlVJRkJ5CmIycGxZM1F4RURBT0JnTlZCQXNNQjFSbGMzUnBibWN4RXpBUkJnTlZCQU1NQ2xOcFoyNXBibWNnUTBFd2daOHcKRFFZSktvWklodmNOQVFFQkJRQURnWTBBTUlHSkFvR0JBTkhHZzhvdmFtYzVxUGtmekRCMk0vZE1WSDBqRjdaZQo4Rlk4VkhlYVFXVWoyaktMd2UzRXdxTEMwOHZkUitvL0k5WHpPM3FaRkI4dVBQUkFVR25hcUVoNmdiL2xMelZwClRKOHkvVTZMSjdaVmtDRlUrOWs1TmdGZkVHekowcG9HQzBUbVBqZXRzb2trQlBpNjJsYkhYcE5xZS9ZeEpDdG8KemJkWjIrUkZwMjZaQWdNQkFBR2pVREJPTUIwR0ExVWREZ1FXQkJRcFBVUVd6ek16elMxZzMwMm5GOUFMMU9Fagp3REFmQmdOVkhTTUVHREFXZ0JSUC9jRmZDY1NucHQvL21KV29NRE1BUVQxRmV6QU1CZ05WSFJNRUJUQURBUUgvCk1BMEdDU3FHU0liM0RRRUJDd1VBQTRHQkFLRHJ1TmlkWUVhNExqajI5aFZ6L21uZ3N4SE12cnZUU0RESlJmcVgKazhWZTdRb09YNndKd2RuYnVBa1dkcUI4eGlMYmxQMUFrRGFzWXBoNEx2WVJoRWozNVhvUHMwSG41ZTNnNkdRNQpxVk9JcnhqSEd4SUhLaGFJeVJiaUtFL0NZUmpRa1ZTM1NZeGFIWmFuM2tkM2o2RkdEcmZCSC9VeTNXZmlpYVVsCjRZNTUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ3REQ0NBaDJnQXdJQkFnSUpBSzl6dVJqakRycEZNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1ITXhDekFKQmdOVgpCQVlUQWtOSU1STXdFUVlEVlFRSURBcENZWE5sYkMxVWIzZHVNUTR3REFZRFZRUUhEQVZDWVhObGJERWJNQmtHCkExVUVDZ3dTUlhKc2FXOGdUVkZVVkNCUWNtOXFaV04wTVJBd0RnWURWUVFMREFkVVpYTjBhVzVuTVJBd0RnWUQKVlFRRERBZFNiMjkwSUVOQk1CNFhEVEUwTURreU5USXdOVEExT1ZvWERUSTBNRGt5TWpJd05UQTFPVm93Y3pFTApNQWtHQTFVRUJoTUNRMGd4RXpBUkJnTlZCQWdNQ2tKaGMyVnNMVlJ2ZDI0eERqQU1CZ05WQkFjTUJVSmhjMlZzCk1Sc3dHUVlEVlFRS0RCSkZjbXhwYnlCTlVWUlVJRkJ5YjJwbFkzUXhFREFPQmdOVkJBc01CMVJsYzNScGJtY3gKRURBT0JnTlZCQU1NQjFKdmIzUWdRMEV3Z1o4d0RRWUpLb1pJaHZjTkFRRUJCUUFEZ1kwQU1JR0pBb0dCQU9TeApyQzA4bXc5VTk1UFpoaFp5Q29CbFVvK2xlTTA1VWdYZzZsTU5XSWsraXJNWnI5U3NHM3ViNjJiNk9MNjFDb1poCkZMOXQ0THNYUU9ORUs3aHVkWmkxQ1NQbDlWT1VmZnFwUGtGMzNtZkp5MDNFSVhGbDV4SHgzVm9UR2dXL1dUOHgKMS90ZXRTY05Hc0tBandFdDBwV2ZxSHFTaGtZS2xkYWVmMk9razRLVkFnTUJBQUdqVURCT01CMEdBMVVkRGdRVwpCQlJQL2NGZkNjU25wdC8vbUpXb01ETUFRVDFGZXpBZkJnTlZIU01FR0RBV2dCUlAvY0ZmQ2NTbnB0Ly9tSldvCk1ETUFRVDFGZXpBTUJnTlZIUk1FQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0R0JBTE90SXJkMDNhVCsKNm5xNi9FM25jM3FyN1BIRXFjQkg4T3ZpdTNsRTlhc1YwV0JubitDRUdZbkZCUno2Y0txcVJIN1BCK1dmaXdEWApMOWFDNWhTY3VZQVN1SnRQS2dKMXFzeE5qbXVZU0E4d1B1V0c2RGRSSkJVYkZoTkhqT0hEcXZ5YW9ZQzR3MVpFClRLd1phSlZyRUZ4L3hUcVA0VzNoOHZoZVVJbzhBRi9JCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: |
    Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgICAgICBTZXJpYWwgTnVtYmVyOiAxICgweDEpCiAgICBTaWduYXR1cmUgQWxnb3JpdGhtOiBzaGEyNTZXaXRoUlNBRW5jcnlwdGlvbgogICAgICAgIElzc3VlcjogQz1DSCwgU1Q9QmFzZWwtVG93biwgTz1FcmxpbyBNUVRUIFByb2plY3QsIE9VPVRlc3RpbmcsIENOPVNpZ25pbmcgQ0EKICAgICAgICBWYWxpZGl0eQogICAgICAgICAgICBOb3QgQmVmb3JlOiBTZXAgMjUgMjA6NTE6MTQgMjAxNCBHTVQKICAgICAgICAgICAgTm90IEFmdGVyIDogU2VwIDI0IDIwOjUxOjE0IDIwMTkgR01UCiAgICAgICAgU3ViamVjdDogQz1DSCwgU1Q9QmFzZWwtVG93biwgTD1CYXNlbCwgTz1TZXJ2ZXIsIE9VPVByb2R1Y3Rpb24sIENOPWxvY2FsaG9zdAogICAgICAgIFN1YmplY3QgUHVibGljIEtleSBJbmZvOgogICAgICAgICAgICBQdWJsaWMgS2V5IEFsZ29yaXRobTogcnNhRW5jcnlwdGlvbgogICAgICAgICAgICAgICAgUHVibGljLUtleTogKDEwMjQgYml0KQogICAgICAgICAgICAgICAgTW9kdWx1czoKICAgICAgICAgICAgICAgICAgICAwMDpjMzo4MTozZjo3ZjphYzoyZDplYzpiMDpiMTplNjoxNTo0OTpiMjplZToKICAgICAgICAgICAgICAgICAgICA5ZjoxNzoyNzo2ZTo5NTozYTo3Njo0ZToyNDplNDowNToyNDpiYzoyNzphMDoKICAgICAgICAgICAgICAgICAgICBlOTplYzphZToyZDphODowNzpjNTo0MzplMzpkOTpjNTo3MzplMzo1ZTo2ZjoKICAgICAgICAgICAgICAgICAgICAyODoyOTowMTo3NzpjMToxZDo0Zjo2YzpjNjphNjo2ZTo4MDpkNzpkZDo3NjoKICAgICAgICAgICAgICAgICAgICAzYjoyYzo1NDpjYjpkOTo1ZDo4YzpjMzpiMzo4NjpkNDpjYzo3NjplMTpmYToKICAgICAgICAgICAgICAgICAgICBhYzowNzo5YTphOTo0MzozMDphYTpkNjplZTo3YTpkYTpkYTowYzphZjo0NToKICAgICAgICAgICAgICAgICAgICA4NDo2YTo1NjpjNzplNjo2Mjo0YjoyODoyZTo4Yzo0ZjpjNjphODo5MTo1OToKICAgICAgICAgICAgICAgICAgICA0Zjo4NjplYTozNTowNTo0NzphZDozNjpiNDo0NjpmYzo0MjpjZTo3NjpmNzoKICAgICAgICAgICAgICAgICAgICBmMDpmNjoxYTozZjoxNDozMzo4Mjo4MzowZgogICAgICAgICAgICAgICAgRXhwb25lbnQ6IDY1NTM3ICgweDEwMDAxKQogICAgICAgIFg1MDl2MyBleHRlbnNpb25zOgogICAgICAgICAgICBYNTA5djMgQmFzaWMgQ29uc3RyYWludHM6IAogICAgICAgICAgICAgICAgQ0E6RkFMU0UKICAgICAgICAgICAgTmV0c2NhcGUgQ29tbWVudDogCiAgICAgICAgICAgICAgICBPcGVuU1NMIEdlbmVyYXRlZCBDZXJ0aWZpY2F0ZQogICAgICAgICAgICBYNTA5djMgU3ViamVjdCBLZXkgSWRlbnRpZmllcjogCiAgICAgICAgICAgICAgICBGNjpGMDowRTo3NTpCRjpGOTo1RjoxQjpBQzo0ODpCNzowODpFNTpDRDoxODo2NDo2NzpCMToyOTozRAogICAgICAgICAgICBYNTA5djMgQXV0aG9yaXR5IEtleSBJZGVudGlmaWVyOiAKICAgICAgICAgICAgICAgIGtleWlkOjI5OjNEOjQ0OjE2OkNGOjMzOjMzOkNEOjJEOjYwOkRGOjREOkE3OjE3OkQwOjBCOkQ0OkUxOjIzOkMwCgogICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgICAgICAgNGY6MTc6NjA6NmE6NGE6MDk6N2Q6MDY6YjE6MjA6MjA6MTY6NTQ6NzQ6ZjY6N2Q6Yzc6YzQ6CiAgICAgICAgIDk5OmEyOmIyOjg3OmEwOmQzOjU4OmJlOjUwOmQwOjNlOjdmOmU3OjBhOmY4OjVhOmI0OjEyOgogICAgICAgICBjMjozYzo1YzphNTpjZjo2MDo5MTo0YjozMzplNTplNzozYzpiNTo3Mzo1YzpmNjpkNTozZDoKICAgICAgICAgZTE6ODk6OGU6ZTg6ZjU6Mzg6MDY6OTY6MjM6Zjc6NDY6OGY6OGE6ZGQ6ZjA6ODI6NWI6MmU6CiAgICAgICAgIDk1OmQwOmZhOmQxOmVhOmRmOmIzOmViOmU5OmY3OjA4OmIzOmRhOjI2OjIzOmQwOjBmOjkzOgogICAgICAgICBiOToyNDo4NjpkYTpkZDpjMjoyNTpmMTo0NjplODo5MjpjMzphMTpkNToyMToyOTo5NzowYzoKICAgICAgICAgNDU6NGE6MGM6ZGQ6MGI6YTg6N2Q6MTQ6YTY6MzU6ZTA6ZjY6Mjc6ZDU6ZTY6Mzc6ZDE6OTk6CiAgICAgICAgIDU3OjdmCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDd3pDQ0FpeWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURCbU1Rc3dDUVlEVlFRR0V3SkRTREVUCk1CRUdBMVVFQ0F3S1FtRnpaV3d0Vkc5M2JqRWJNQmtHQTFVRUNnd1NSWEpzYVc4Z1RWRlVWQ0JRY205cVpXTjAKTVJBd0RnWURWUVFMREFkVVpYTjBhVzVuTVJNd0VRWURWUVFEREFwVGFXZHVhVzVuSUVOQk1CNFhEVEUwTURreQpOVEl3TlRFeE5Gb1hEVEU1TURreU5ESXdOVEV4TkZvd2JERUxNQWtHQTFVRUJoTUNRMGd4RXpBUkJnTlZCQWdNCkNrSmhjMlZzTFZSdmQyNHhEakFNQmdOVkJBY01CVUpoYzJWc01ROHdEUVlEVlFRS0RBWlRaWEoyWlhJeEV6QVIKQmdOVkJBc01DbEJ5YjJSMVkzUnBiMjR4RWpBUUJnTlZCQU1NQ1d4dlkyRnNhRzl6ZERDQm56QU5CZ2txaGtpRwo5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUF3NEUvZjZ3dDdMQ3g1aFZKc3U2ZkZ5ZHVsVHAyVGlUa0JTUzhKNkRwCjdLNHRxQWZGUStQWnhYUGpYbThvS1FGM3dSMVBiTWFtYm9EWDNYWTdMRlRMMlYyTXc3T0cxTXgyNGZxc0I1cXAKUXpDcTF1NTYydG9NcjBXRWFsYkg1bUpMS0M2TVQ4YW9rVmxQaHVvMUJVZXROclJHL0VMT2R2Znc5aG8vRkRPQwpndzhDQXdFQUFhTjdNSGt3Q1FZRFZSMFRCQUl3QURBc0JnbGdoa2dCaHZoQ0FRMEVIeFlkVDNCbGJsTlRUQ0JIClpXNWxjbUYwWldRZ1EyVnlkR2xtYVdOaGRHVXdIUVlEVlIwT0JCWUVGUGJ3RG5XLytWOGJyRWkzQ09YTkdHUm4Kc1NrOU1COEdBMVVkSXdRWU1CYUFGQ2s5UkJiUE16UE5MV0RmVGFjWDBBdlU0U1BBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRHQkFFOFhZR3BLQ1gwR3NTQWdGbFIwOW4zSHhKbWlzb2VnMDFpK1VOQStmK2NLK0ZxMEVzSThYS1hQCllKRkxNK1huUExWelhQYlZQZUdKanVqMU9BYVdJL2RHajRyZDhJSmJMcFhRK3RIcTM3UHI2ZmNJczlvbUk5QVAKazdra2h0cmR3aVh4UnVpU3c2SFZJU21YREVWS0ROMExxSDBVcGpYZzlpZlY1amZSbVZkLwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUREZ1Q5L3JDM3NzTEhtRlVteTdwOFhKMjZWT25aT0pPUUZKTHdub09uc3JpMm9COFZECjQ5bkZjK05lYnlncEFYZkJIVTlzeHFadWdOZmRkanNzVk12WlhZekRzNGJVekhiaCtxd0htcWxETUtyVzducmEKMmd5dlJZUnFWc2ZtWWtzb0xveFB4cWlSV1UrRzZqVUZSNjAydEViOFFzNTI5L0QyR2o4VU00S0REd0lEQVFBQgpBb0dBRWJrRXZaa3BMSnl6ODh5WU9yMUE5TU5oVmV2UHo3T3VhL3p4aFpJandvM2ptNmpnckEvYXJQaWRjdkVXCnJlanhKek4yQU1GZFV3VWhESFZzVmM5MkR4eUlsYTdzOFl0TlFWWFFXMEFMVGdqNVExV3BzeVBqeTZjTHZINGUKTFR6MzQrVURRNm8veHJJY2tiQ0pORXZZQnJiRldxMWtGYkhrSEgxWjBlRCt0TGtDUVFENklEUGpuNGt0TDdpeQovK1hhRDFpRmZWZEZSMlZQZnFzRStoaGIzcDkwQy9nYmFmVXdvSGU2RzQ5RU1pOTZjbW5IamNQaTBVK0lHS0t6CjFMbjdoZFViQWtFQXlCaW55cDZVNklwUHpMK3hMdGg3QW14RW9WdHBsR3piVXJVc0JoWDlVM1hySW1HZjJuQ3UKemo4TTJDeEFrOXpMMnk3TGFReFJjM2tVWWNxYlFBVU5IUUpBT2ZveTdPVXk3OVZxODVyYlZZTlBHb29tSzNuVQpJdXdTaWpIS2Fha2R2dEZ6Ymk5T1ZUb3M1bWV5K3JURFNwZXdxei9TRXdZL2NDVjl1VDlxNk1GcDF3SkFiaHFUCkNiMWxOdWdVclJlMkNZNzVjUVhlWmVPRkh6VWZJazJxNGRacnhPY1g4WjFDZHRLV2Zjclg2SVBCTFJ2TDJOblEKK0FiZE11c25PZ0JnbVVPdVNRSkJBSUNxQ05pTkJBZTZOYm8zQTEzK3RYeEtQbys0UDhIVFBTMldDTzZhWjFTUgp3QnVFRXNyTG44R05iMmJIQ0NMZjNFTy9JTmcxQ0JmTmNxVHZNcEVsV3lBPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

finally I use kubectl port-forwarder 8883:8883 to connect from mqtt explorer to the pod with no success

From my investigations it looks that it could be a permissions problem from certificates files, but my guess is that it should be solved in the chart. any ideas?

**Comment by ioolkos** [comment]
@isidnis look at the logs when Verne starts. Is the SSL listener actually up or not?
