### ISSUE TITLE
New version 1.12.1 results in /lib/env.sh: No such file or directory

### ISSUE THREAD

**Issue by JeremyTheocharis** [vernemq/docker-vernemq#292]
Hi together,

we just realized that the new version jump from 1.11.0 to 1.12.1 results in minikube and k3s in an error `/lib/env.sh: No such file or directory`

Using the previous version 1.11.0 fixed the issue for us.

See also: https://github.com/united-manufacturing-hub/united-manufacturing-hub/issues/375

Greetings from Germany!
Jeremy

**Comment by ioolkos** [comment]
@JeremyTheocharis thanks, ugh, that's bad. I was thinking I had this fixed. It's a path issue. I need to investigate.

**Comment by desmondsow** [comment]
Hi @ioolkos,

Both `1.12.1` and `1.12.1-alpine` is failing. Something is wrong with the latest VerneMQ binary. Replacing it with version `1.12.0` fixed the issue.

```
/vernemq/bin/vernemq: line 8: /lib/env.sh: No such file or directory
/vernemq/bin/vernemq: line 140: check_user_internal: command not found
/vernemq/bin/vernemq: line 144: create_pid_dir: command not found
/vernemq/bin/vernemq: line 147: echoerr: command not found
```

**Comment by ioolkos** [comment]
@desmondsow okay, thanks for letting me know.

**Comment by beckerben** [comment]
Confirmed, i observe the same!

**Comment by ioolkos** [comment]
@beckerben thanks, I'm still on it. I deleted all the related packages. I'll have packages for 1.12.1 up again in the next couple of days.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.

**Comment by SebUndefined** [comment]
Could you please give us an update ? We observe that on our cluster. Thanks in advance ! :)

**Comment by ioolkos** [comment]
The issue is fully identified. The Docker images pull the tarballs from the release binaries here on Github. Due to a patch to adjust the correct paths on .deb and .rpm packages, the tarballs had wrong internal paths set, making the Docker images unusuable.

New images should be up soon, but please bear with me, it's more work than it might sound like.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.

**Comment by SebUndefined** [comment]
Don't worry, it actually sounds like a lot of work ;).

**Comment by ioolkos** [comment]
I've now manually uploaded local builds for 1.12.1 and 1.12.1-alpine. Could you guys give them a test, regarding original issue? https://hub.docker.com/repository/docker/vernemq/vernemq/tags?page=1&ordering=last_updated

Thanks!

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.

**Comment by SebUndefined** [comment]
I will try it tomorrow ! Thanks for your quick action !

**Comment by JeremyTheocharis** [comment]
Hi,

Either me or someone of my team will test it in the upcoming days. Looking forward to it!

@kruegeralex
@larswitte
@scarjit

**Comment by Scarjit** [comment]
@JeremyTheocharis Deployed our stack with 1.12.1, vernemq starts successfully.
![screenshot](https://cloud.soontm.net/s/WD9ZPE8rNkfpJQX/preview)

**Comment by SebUndefined** [comment]
@ioolkos I confim that the image 1.12.1 works. VMQ starts normally. Thank you for your effort !

**Comment by ioolkos** [comment]
@SebUndefined, @Scarjit great, thanks for your testing & feedback!

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.

**Comment by jforge** [comment]
Thanks for this. The latest tag on docker hub is still on a version having this error => Could you also tag this, so that the masses of examples in the web do not fail in the beginning?

**Comment by ioolkos** [comment]
@jforge makes sense, will do that.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.
