### ISSUE TITLE
Using pure Docker commands not working

### ISSUE THREAD

**Issue by gopimails** [vernemq/docker-vernemq#295]
I followed this [https://github.com/vernemq/docker-vernemq#3-using-pure-docker-commands](url)

Tried this 
`docker run -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" --name vernemq1 -d vernemq/vernemq
`

and getting this 

> /vernemq/bin/vernemq: line 8: /lib/env.sh: No such file or directory
> /vernemq/bin/vernemq: line 140: check_user_internal: command not found
> /vernemq/bin/vernemq: line 144: create_pid_dir: command not found
> /vernemq/bin/vernemq: line 147: echoerr: command not found

Please help resolve this and appreciate if you can update the docs.

**Comment by ioolkos** [comment]
@gopimails Thanks... do you use a locally cached Docker image? If I'm not mistaken that error should be fixed in 1.12.1.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.

**Comment by gopimails** [comment]
@ioolkos 

I did not had a local copy.
```
$ docker run -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" --name vernemq1 -d vernemq/vernemq
Unable to find image 'vernemq/vernemq:latest' locally
latest: Pulling from vernemq/vernemq
Digest: sha256:e56d27292375e69c03c4ad062baeeb0b0a593e216e1270d215d3db4cb5b27e60
Status: Downloaded newer image for vernemq/vernemq:latest
82aaacb14ac236ed369f499ceb970c8f66d3f6145cfd5ab6ce72e2bf08bea1f0

$ 
```
and it exited immediately with log
```
docker logs --tail 1000 -f 82aaacb14ac236ed369f499ceb970c8f66d3f6145cfd5ab6ce72e2bf08bea1f0 <

/vernemq/bin/vernemq: line 8: /lib/env.sh: No such file or directory
/vernemq/bin/vernemq: line 140: check_user_internal: command not found
/vernemq/bin/vernemq: line 144: create_pid_dir: command not found
/vernemq/bin/vernemq: line 147: echoerr: command not found
```

When I inspect, it says "VERNEMQ_VERSION=1.12.1"

**Comment by ioolkos** [comment]
@gopimails "latest" is broken, apologies. Use the tagged releases for now. I need to replace the "latest" package.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.

**Comment by ioolkos** [comment]
@gopimails I manually pushed "latest" builds to Dockerhub. Those should be the same as 1.12.1.
Feel free to test and report issues.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.

**Comment by gopimails** [comment]
It works now. Thank you.
