### ISSUE TITLE
Newest VerneMQ Helm chart is not available under https://vernemq.github.io/docker-vernemq

### ISSUE THREAD

**Issue by mstavrev** [vernemq/docker-vernemq#298]
Hello,

I see VerneMQ's most recent release is 1.12.2 from 2nd of September 2021. The helm chart's Chart.yaml had been updated on 4th of September to reference it on its version 1.6.10-1/app version 1.12.1-1. 
However, if you list the https://vernemq.github.io/docker-vernemq repo you'd get:

> [local-k8s@dev01 vernemq]$ helm search repo -l vernemq                                   
> NAME            CHART VERSION   APP VERSION     DESCRIPTION                                       
> vernemq/vernemq 1.6.7           1.11.0          VerneMQ is a high-performance, distributed MQTT...
> vernemq/vernemq 1.6.6           1.11.0          VerneMQ is a high-performance, distributed MQTT...
> vernemq/vernemq 1.6.5           1.10.4.1        VerneMQ is a high-performance, distributed MQTT...
> ...

Looks like the helm repo had been updated last on Nov 24, 2020 and does not contain any newer release of VerneMQ ever since.
Is this some kind of Travis-CI issue?

**Comment by ioolkos** [comment]
@mstavrev Thanks... Travis-CI issue, yes.

**Comment by mstavrev** [comment]
When do you think the chart shall be in sync?

**Comment by ioolkos** [comment]
@mstavrev @onedr0p I'll look into moving the .travis.yml functions to Github Actions. It does not have the highest priority for me right now. Apologies, in any case.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by onedr0p** [comment]
I'm starting to think that pretty much the case, this has already been ignored for the past year. I've moved onto emqx. Sorry.

**Comment by ioolkos** [comment]
@onedr0p allright, good luck!

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@mstavrev I've manually added helm-1.6.12 (Verne 1.12.3). Please let me know should this not work.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
1.12.3 now shows in the helm list

```sh
➜  docker-vernemq git:(master) sudo helm search repo -l vernemq
NAME           	CHART VERSION	APP VERSION	DESCRIPTION                                       
vernemq/vernemq	1.6.12       	1.12.3     	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.6.7        	1.11.0     	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.6.6        	1.11.0     	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.6.5        	1.10.4.1   	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.6.3        	1.10.3     	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.6.2        	1.10.2     	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.6.1        	1.10.1     	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.5.1        	1.10.1     	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.5.0        	1.10.0     	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.4.4        	1.9.2      	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.4.3        	1.9.2      	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.4.2        	1.9.1      	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.4.1        	1.9.1      	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.4.0        	1.9.0      	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.3.0        	1.8.0      	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.2.0        	1.7.1-1    	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.1.0        	1.7.1-1    	VerneMQ is a high-performance, distributed MQTT...
vernemq/vernemq	1.0.0        	1.7.1-1    	VerneMQ is a high-performance, distributed MQTT...
```
---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mstavrev** [comment]
Thank you. I see it is updated now. Unfortunately and attempt to install or upgrade to 1.6.12 leads to the problem opened as issue #300.
