### ISSUE TITLE
Vernemq HTTP API KEY

### ISSUE THREAD

**Issue by neel8989** [vernemq/docker-vernemq#299]
Is this possible to pass vernemq http API key through helm deployment file ?

Currently we are using this command to add API key
vmq-admin api-key add key=mykey
@vmq-ci @ioolkos

**Comment by eyenx** [comment]
This was implemented in this PR https://github.com/vernemq/docker-vernemq/pull/369 but not for the helm chart as it uses still version 1.13.0 of the docker image. So I guess it needs a new release for this to be included in the helm chart 

Right @ioolkos ? 

When is this expected to happen?

**Comment by ioolkos** [comment]
@eyenx yes, it needs a new release/Helm release yes, unless you want to mount any new or adapted start script into the Docker image.

---
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq

**Comment by eyenx** [comment]
@ioolkos where is the new release?

**Comment by ioolkos** [comment]
@eyenx our official images are on Dockerhub, and you can update your helm repository to get the newest release. But I also just added a 2.0.1 tag.

---
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq

**Comment by eyenx** [comment]
Thank you @ioolkos !

Very much appreciate this
