### ISSUE TITLE
helm chart installation error

### ISSUE THREAD

**Issue by sdavid63** [vernemq/docker-vernemq#310]
Hello,
I try to install vernemq via helm charts on my ovhcloud managed kubernetes service (1.22.2-2) but i have the following error

sdavid@ubv8-r2d2:~$ helm install vernemq/vernemq --generate-name
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/sdavid/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/sdavid/.kube/config
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].envFrom): invalid type for io.k8s.api.core.v1.Container.envFrom: got "map", expected "array"

What i'm doing wrong ?

Thank you

**Comment by agronholm** [comment]
You're not doing anything wrong – the chart is broken. The problem has been fixed since but no update has been released.

**Comment by agronholm** [comment]
The workaround for that particular problem is to define `envFrom: []` under `vernemq`.

**Comment by chenxinlong** [comment]
I'm new to kubernetes and helm, my problem is failed to download vernemq charts on my MacOS like pic below : 
<img width="974" alt="image" src="https://user-images.githubusercontent.com/9261954/180618460-4e8b6de4-64c3-486c-aebf-f32fd2cfcc52.png">

Is that the same problem you mentioned upon "the chart is broken" ?   @agronholm Thank you.

**Comment by agronholm** [comment]
> Is that the same problem you mentioned upon "the chart is broken" ? @agronholm Thank you.

No. You don't have the `vernemq` repository added.

**Comment by mojoscale** [comment]
Any update on the fix for helm chart?

**Comment by maelp** [comment]
How do you add the vernemq repository? there's no explanation in the documentation?

**Comment by agronholm** [comment]
> How do you add the vernemq repository? there's no explanation in the documentation?

It's right at the start, [here](https://github.com/vernemq/docker-vernemq#2-using-helm-to-deploy-on-kubernetes).

**Comment by ioolkos** [comment]
@maelp 
`helm repo add vernemq https://vernemq.github.io/docker-vernemq`

`helm search repo -l vernemq`
Does this help?

**Comment by maelp** [comment]
Thanks :) would be perhaps useful to add this to the README ;)

**Comment by agronholm** [comment]
> Thanks :) would be perhaps useful to add this to the README ;)

Huh? I literally just pointed out where it is in the README!

**Comment by ioolkos** [comment]
@agronholm @maelp Thanks for helping out! I need more coffee too :)

**Comment by maelp** [comment]
Thanks @agronholm @ioolkos 

When installing the latest Helm chart on GKE Autopilot, I have a CrashLoopBackoff of the pod, I tried using `envFrom: []` (but it seems to be the default in `values.yaml` now anyway) and it doesn't seem to change anything

Do you know if the latest version (1.8.1) is working, or should we downgrade the version?

```
    error: update failed

  kubernetes:apps/v1:StatefulSet (vernemq/vernemq):
    error: 3 errors occurred:
    	* the Kubernetes API server reported that "vernemq/vernemq" failed to fully initialize or become live: 'vernemq' timed out waiting to be Ready
    	* 0 out of 1 replicas succeeded readiness checks
    	* [Pod vernemq/vernemq-0]: containers with unready status: [vernemq] -- [CrashLoopBackOff] back-off 5m0s restarting failed container=vernemq pod=vernemq-0_vernemq(e9c48636-2cc6-4364-8432-0869f1af9bec)
```

This is how I install the chart (using Pulumi)

```
chart_ns = Namespace("vernemq", metadata=ObjectMetaArgs(name="vernemq"))
chart = Chart(
    "vernemq",
    config=ChartOpts(
        fetch_opts={"repo": "https://vernemq.github.io/docker-vernemq"},
        chart="vernemq",
        version="1.8.1",
        namespace=chart_ns.metadata.name,
        values={
            "envFrom": []  # To fix installation issue https://github.com/vernemq/docker-vernemq/issues/300
        },
    ),
    opts=pulumi.ResourceOptions(provider=k8s_provider, depends_on=[chart_ns]),
)
```

**Comment by maelp** [comment]
(for the README, I was speaking about the one in the Helm chart dir, which does not mention the repo https://github.com/vernemq/docker-vernemq/blob/master/helm/vernemq/README.md)

**Comment by ioolkos** [comment]
@maelp can't really help on GKE Autopilot and Pulumi. Is there a way to get to more logs?

**Comment by maelp** [comment]
Okay seems that now it works, perhaps I had forgotten to set `DOCKER_VERNEMQ_ACCEPT_EULA`
