### ISSUE TITLE
Container Crashes on DOCKER_VERNEMQ_ALLOW_MULTIPLE_SESSIONS

### ISSUE THREAD

**Issue by cyronis** [vernemq/docker-vernemq#351]
Hi there,

I tried to run the new Version of Vernemq 1.12.6.2 with my Helm Chart and as soon as I enable 
DOCKER_VERNEMQ_ALLOW_MULTIPLE_SESSIONS = on
it keeps crashing - 
when I set it to off or with the Version 1.12.3 the container starts without a problem

this i the only thing i get out of the container
-config /vernemq/data/generated.configs/app.2023.03.05.15.52.35.config -args_file /vernemq/bin/../etc/vm.args -vm_args /vernemq/bin/../etc/vm.args

BR

**Comment by ioolkos** [comment]
@cyronis while it still might be interesting to find out why, note that the `allow_multiple_sessions` feature is in deprecation.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
