### ISSUE TITLE
join_cluster missing in alpine image?

### ISSUE THREAD

**Issue by micw** [vernemq/docker-vernemq#370]
The Dockerfile copies "join_cluster.sh", in Dockerfile.aloine it's missing. I guess it's just forgotten there?

**Comment by ioolkos** [comment]
@micw Thanks. Good catch, the Alpine file will also need this.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by micw** [comment]
BTW, what is the purpose of this file? Seems to be referenced at no place except the Dockerfile.
Same with `rand_cluster_node.escript` - it's in bin but not even referenced from any Dockerfile.

**Comment by ioolkos** [comment]
It' used to retry cluster joins. See https://github.com/vernemq/docker-vernemq/blob/02b0bdc381e56da814aa7f4a429ea7b679f4022c/bin/vernemq.sh#L346C5-L346C17
`rand_cluster_node` is not used anymore. It served to select a random cluster node.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
should be fixed now. (2.0.0 images)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
