### ISSUE TITLE
Hard to understand k8s secret name in Helm chart for TLS certificates

### ISSUE THREAD

**Issue by mrceyhun** [vernemq/docker-vernemq#371]
Hi folks,

In values.yaml file[1] also in README.md[2], I see secret name as `vernemq-certificates-secret` for TLS certificates, however in StatefulSet template[3] it is defined as `secretName: {{ include "vernemq.fullname" . }}-certs` which will be `vernemq-certs` if default full name is not overwritten.

Is there any mistake or am I missing something? Thank you in advance ❤️ 

[1] https://github.com/vernemq/docker-vernemq/blob/7eb6ab3fe8d11bd334e3b65f953105a0f597bc44/helm/vernemq/values.yaml#L173-L178
[2] https://github.com/vernemq/docker-vernemq/blob/7eb6ab3fe8d11bd334e3b65f953105a0f597bc44/helm/vernemq/README.md?plain=1#L156
[3] https://github.com/vernemq/docker-vernemq/blob/7eb6ab3fe8d11bd334e3b65f953105a0f597bc44/helm/vernemq/templates/statefulset.yaml#L196

**Comment by ioolkos** [comment]
Must have been introduced by this commit: https://github.com/vernemq/docker-vernemq/commit/ddc6ee6c8f8432620941bfb27d8c82d278c1f2fa
Do you see an issue with it? What would be your proposed solution? (as I understand, it's an inconsistency in docs and yaml files where outcommented values might be misleading)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mrceyhun** [comment]
To be compatible, should not the `secretName: vernemq-certificates-secret ` name be `vernemq-certs`? That's why I asked if I am missing something. Are they different secrets?

**Comment by ioolkos** [comment]
In my view `vernemq-certificates-secret` is just an example name. The PR mentioned above introduced an additional way to configure TLS certs over helm values. You'll have to choose how to setup the secrets. (And yes, it's always about the TLS secrets (server certs & key) here).

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mrceyhun** [comment]
Thanks a lot @ioolkos , that's what I'm trying to be sure 👍
