### ISSUE TITLE
vmq-admin

### ISSUE THREAD

**Issue by Guggs** [vernemq/docker-vernemq#393]
vmq-admin

expected respond:

pong

i get

Node 'VerneMQ@... not responding to pings.

**Comment by ioolkos** [comment]
Most likely, the VerneMQ node is not running then.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by Guggs** [comment]
It has to run, i can connect to it, publish and subscribe to topics.
