### ISSUE TITLE
Regarding building with source

### ISSUE THREAD

**Issue by subhasniveus** [vernemq/docker-vernemq#396]
We are building vernemq using source as per the instruction provided here : https://vernemq.com/downloads/

Initially, Erlang OTP was installed using binary and we faced the same issue so again we installed using the repository way as mentioned here https://www.erlang-solutions.com/downloads/#

We followed the instructions, installed necessary libraries and the build was successful. 

We ran the vernemq and it worked fine. 

Next step, we tried to containerize so that we could deploy on a server. We used the alipne version mentioned here : https://github.com/vernemq/docker-vernemq/blob/master/Dockerfile.alpine

Below is the content

```
FROM alpine:3.20.0

RUN apk --no-cache --update --available upgrade && \
    apk add --no-cache ncurses-libs libstdc++ snappy-dev nano && \
    addgroup --gid 10000 vernemq && \
    adduser --uid 10000 -H -D -G vernemq -h /vernemq vernemq && \
    install -d -o vernemq -g vernemq /vernemq

# Defaults
ENV DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR="app=vernemq" \
    DOCKER_VERNEMQ_LOG__CONSOLE=console \
    PATH="/vernemq/bin:$PATH" 

WORKDIR /vernemq

# copy the release files. this is instead of the binary
COPY . . 

# Note that the following copies a binary package under EULA (requiring a paid subscription).
RUN chown -R 10000:10000 /vernemq && \
    ln -s /vernemq/etc /etc/vernemq && \
    ln -s /vernemq/data /var/lib/vernemq && \
    ln -s /vernemq/log /var/log/vernemq

# Ports
# 1883  MQTT
# 8883  MQTT/SSL
# 8080  MQTT WebSockets
# 44053 VerneMQ Message Distribution
# 4369  EPMD - Erlang Port Mapper Daemon
# 8888  Health, API, Prometheus Metrics
# 9100 9101 9102 9103 9104 9105 9106 9107 9108 9109  Specific Distributed Erlang Port Range

EXPOSE 1883 8883 8080 44053 4369 8888 \
       9100 9101 9102 9103 9104 9105 9106 9107 9108 9109


VOLUME ["/vernemq/log", "/vernemq/data", "/vernemq/etc"]

HEALTHCHECK CMD vernemq ping | grep -q pong

USER vernemq

CMD ["vernemq", "start"]
```

The image is built fine. When we try to run the image it throws below error 

> /vernemq/bin/vernemq: line 189: /vernemq/bin/../erts-14.2.1/bin/run_erl: not found
> vmq_cluster_node_sup

The run_erl file is present at the mentioned location but for some reason shows not found. 

Similarly, when we try to execute `vernemq console` it throws below error

> /vernemq/bin/vernemq: line 139: /vernemq/bin/../erts-14.2.1/bin/escript: not found

Here again escript file is present.

Any help is greatly appreciated to resolve this error. Thanks.

**Comment by ioolkos** [comment]
Apologies, I cannot help with build issues.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
