### ISSUE TITLE
Testing the dockerfile

### ISSUE THREAD

**Issue by larshesel** [vernemq/docker-vernemq#40]
Hi all,

As the Dockerfile grows more complex, I was thinking about a way to test that we don't break anything and a quick google search found goss: https://github.com/aelsabbahy/goss and this tutorial: https://medium.com/@aelsabbahy/tutorial-how-to-test-your-docker-image-in-half-a-second-bbd13e06a4a9

As I'm no Docker expert I'd find it very nice if we had an easily extensible test-suite to make sure that old features don't break and new features/bugfixes will actually work.

Do you think something like this would be worthwhile? What other ways are there of testing Dockerfiles?

/cc @drf @dergraf

**Comment by drf** [comment]
Didn't know about Goss TBH, but will gladly do my homework over the next days.

Anyway, we're already using Travis for building and testing docker images, so setting up a "traditional" CI pipeline is probably a very good idea.

Also, as we already discussed, it would be probably a good idea to think about moving to multistage builds (https://docs.docker.com/develop/develop-images/multistage-build/)
