### ISSUE TITLE
How to setup docker-vernemq on Docker Swarm

### ISSUE THREAD

**Issue by mitchellvanrijkom** [vernemq/docker-vernemq#43]
### Environment
VerneMQ Version: None
OS: Docker Swarm (Docker images based on Alpine or Ubuntu)
Erlang/OTP version (if building from source):

### Expected behavior
3 node VerneMQ cluster running in Docker Swarm with Docker services/stacks

### Actual behaviour
Unknown. I can't find this use case in the documentation and it would be very, very nice to have it!
There is some documentation about starting a Docker container. But Docker swarm works with services/stacks that are available between the nodes.
Is it even possible to run as a service/stack or do you have start it manually on different servers?

We are comparing different MQTT brokers and those who appeal to us the most are VerneMQ and EMQ. We would like to run it in our production system but want to have native Docker Swarm support.

Thanks in advance!

**Comment by ioolkos** [comment]
Hey @mitchellvanrijkom totally sorry, missed your issue here somehow. My apologies. 
Let's see. What would native Docker Swarm support mean? is there anything specific we'd need to enable or script?

**Comment by mitchellvanrijkom** [comment]
Hey @ioolkos No problem! Thanks for the reply. 
Docker Swarm is a clustering and orchestration tool for running Docker containers in Services.
https://docs.docker.com/engine/swarm/
To make use of scaling applications and enable load-balancing in the swarm we use Docker Services. This is one level up in the hierarchy of a distributed application of docker. See, https://docs.docker.com/get-started/part3/. 

What we would like is when we have deployed VerneMQ broker as a Service. We want to make use of the scaling functionality in docker swarm to scale the numbers of running containers to autojoin a VerneMQ cluster by a simple command instead of defining own containers with the docker run command. See Docker documentation about scaling a service:  https://docs.docker.com/engine/swarm/swarm-tutorial/scale-service/.  When you want to use Autojoining you are required to set a IP-address of the first VerneMQ container. In a Docker swarm we can make use of Service discovery. Swarm manager nodes assign each service in the swarm a unique DNS name and load balances running containers. You can query every container running in the swarm through a DNS server embedded in the swarm. Thereby no need to set an IP-address.  

Let me know if i am unclear in my explanation. 

Thanks in advance!

**Comment by dergraf** [comment]
@mitchellvanrijkom I guess this issue might be solved as part of our work in https://github.com/vernemq/vmq-discovery cc: @ioolkos, @codeadict

**Comment by codeadict** [comment]
Yes, that will be possible with vmq-discovery indeed.

**Comment by JesusIslam** [comment]
Any update for this? I've looked at vmq-discovery but the repo is so bare.

**Comment by codeadict** [comment]
Not yet, vmq-discovery is being worked slowly, work starting new year,
contributions always welcome :)
