### ISSUE TITLE
Question: ARM support for Docker on Raspberry Pi

### ISSUE THREAD

**Issue by SeppPenner** [vernemq/docker-vernemq#58]
Hi, is there (or will there be) an official option to run VerneMQ on Docker on an ARM platform like the Raspberry Pi?

I have tried to modify the original Dockerfile to the following example: https://gist.github.com/SeppPenner/08ef2a0593e30e0091351a7cb7932df4

However, I get the issue:

```
Err http://security.debian.org jessie/updates InRelease

Err http://security.debian.org jessie/updates Release.gpg
Unable to connect to security.debian.org:http: [IP: 212.211.132.250 80]
```

I have tried this on my private Raspberry Pi as well as on a company's (Which is behind a proxy) and did get the same result.

**Comment by dergraf** [comment]
Currently there isn't an 'official' option. And we'd suggest to compile VerneMQ for RPI directly (using `make rpi-32` instead of using our Debian package (installed by the Dockerfile), as this isn't built for ARM.

However we could think of pushing a Docker image compatible with ARM to dockerhub, however I am not sure how the demand is for such an image.

**Comment by SeppPenner** [comment]
@dergraf Depending on how much effort it is for you... I think it would be interesting for more people than just for me. Plus, e.g. RabbitMQ (competitor) has such an image, too: https://github.com/docker-library/rabbitmq/issues/153, https://hub.docker.com/_/rabbitmq/

**Comment by dergraf** [comment]
Do you know if it would be possible to build such an image using the automated Docker builds from dockerhub? Or would we need an ARM powered host to run `docker build` ?

**Comment by codeadict** [comment]
We use resin(now balena.io)a lot t work, i'll try to create an image for ARM this weekend that publishes to docker hub

**Comment by SeppPenner** [comment]
@codeadict That would be a pretty cool thing :) 👍

**Comment by jsilence** [comment]
@codeadict any news about the ARM docker hub image?

**Comment by kolektiv** [comment]
I've played around with this a little this afternoon (without a lot of success, but I'm not an expert on Docker, Erlang, or VerneMQ, which is probably a handicap). Could I ask a couple of questions? What's the difference between the rpi32 and the release target for the build (what's the goal of the difference I guess). The main release target seems to build a bit more as output - admin tools? The new builder support in Docker for cross compiling does seem to make this a bit easier to support, and it would be great to have!

**Comment by kolektiv** [comment]
Oh, and a little bit of motivation - VerneMQ seems to be great for running on a Pi cluster now that Pi4 is here with a bit more grunt - either via Kubernetes or Swarm, but it would be awesome to have an ARM image available officially!

**Comment by larshesel** [comment]
hi @kolektiv the `rpi32` branch uses a modified erlang driver for eleveldb as raspian is (was?) 32 bit only which prevented the eleveldb code from compiling.

**Comment by kolektiv** [comment]
Hi @larshesel - thanks. I'm playing around with the docker images for rpi32, and not having 100% success - the output of the rpi32 target doesn't seem to match the others, but maybe I'm missing something!

**Comment by larshesel** [comment]
Closing this as there are currently no plans to support RPI docker images - it would have to be a community effort.

**Comment by tbrand-aa** [comment]
I've managed to get the alpine docker version build on a RaspberryPi 4, and it seems running fine.
If there are still people interested, I will get this public.

**Comment by romor001** [comment]
Please do! Would be much appreciated!

**Comment by tbrand-aa** [comment]
Sorry for the delayed reply, here is the Docker Image:
https://hub.docker.com/r/timbrand/vernemq-rpi
I'm using it for about a week now in my home automation, works great.

**Comment by tkerby** [comment]
Really glad to see this @tbrand-aa Would love to have official support though.
