### ISSUE TITLE
docker pause/restart doesn't work

### ISSUE THREAD

**Issue by dergraf** [vernemq/docker-vernemq#66]
The main reason for this is that it adds the `node_join` command to the vm.args every time the container gets started. Moreover it actually messes with a previous `--eval` inside the vm.args. 
To fix this issue one should only add the `node_join` command the first time the node is started, and actually only evaluate it if the node hasn't joined a cluster before. So this needs some work.

Workaround for now, don't use pause/restart. ;)

**Comment by cars10w** [comment]
I guess you can close this bug since it is avoided [here](https://github.com/vernemq/docker-vernemq/blob/master/bin/vernemq.sh#L14).

**Comment by dergraf** [comment]
good catch, thanks
