### ISSUE TITLE
Kubernetes namespace could be detected automatically

### ISSUE THREAD

**Issue by francois-travais** [vernemq/docker-vernemq#70]
When using the kubernetes clustering mechanism, one has to set the environment variable `DOCKER_VERNEMQ_KUBERNETES_NAMESPACE`.

While this method works fine there is a way to find the namespace in which the pod runs, it's stored in a file named `namespace` alongside `ca.crt` and `token` in `/var/run/secrets/kubernetes.io/serviceaccount/`.

**Comment by juusujanar** [comment]
Just a note, that there's a default value in Dockerfile using ENV, which means the cat result is ignored because env is set.
