### ISSUE TITLE
Docker container errors (at least for me) on nightly 1.5.0 (1.5.0-127-ge130553)

### ISSUE THREAD

**Issue by xbugster** [vernemq/docker-vernemq#72]
Hello,
Container failing to start with error that "start_vernemq" is not found in $PATH
actual fix is 
https://github.com/erlio/docker-vernemq/blob/0501ac840ff068d29d0bf460e07b445f2980636f/Dockerfile#L53
needs to be change to
```CMD ["bash", "/usr/sbin/start_vernemq"]``` which composes command `bash /usr/sbin/start_vernemq`
As the start_vernemq is moved to mentioned directory at https://github.com/erlio/docker-vernemq/blob/0501ac840ff068d29d0bf460e07b445f2980636f/Dockerfile#L26

Actually, the bash script is there, but shell can not find it in $PATH, so running it explicitly with bash solves it.
using `bash path_to_sh_script` solves the issue for those encountering such error.

**Comment by dergraf** [comment]
Thanks for the report!
How did you build the image?

**Comment by xbugster** [comment]
> 
> 
> Thanks for the report!
> How did you build the image?

`docker build .`

**Comment by dergraf** [comment]
@xbugster can you check with the latest changes to our Docker image?
