### ISSUE TITLE
Clustering fails when k8s cluster is not "cluster.local"

### ISSUE THREAD

**Issue by cbluth** [vernemq/docker-vernemq#74]
When the kubernetes cluster is named something other than `cluster.local`, then vernemq clustering fails.

See here: https://github.com/erlio/docker-vernemq/blob/ec8ffe2bba98c7a8cc96e7e471cc3118f93e2c24/bin/vernemq.sh#L32

```
root@vernemq-0:~# vmq-admin cluster show
Node 'VerneMQ@vernemq-0..backend.svc.cluster.local' not responding to pings.
root@vernemq-0:~# 
```

**Comment by francois-travais** [comment]
I'm not sure that the cluster name is to blame here, there is no namespace in the nodename URL. This may be related to #70

**Comment by cbluth** [comment]
what happens if the FQDN of the clusterip kubernetes api is `kubernetes.default.svc.cluster2.local` instead of `kubernetes.default.svc.cluster.local`?

**Comment by cbluth** [comment]
using kubespray and changing the value here: https://github.com/kubernetes-incubator/kubespray/blob/master/inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml#L109-L110

changing that value will cause vernemq to fail when joining the cluster.

**Comment by zeisi** [comment]
I'm having the same problem, it looks like the subdomain gets set, even if it's empty.
https://github.com/vernemq/docker-vernemq/blob/2cd43171c30bf44ca88c53be76b01ebd786d2ae6/bin/vernemq.sh#L28-L33

In line 29, there is a call to curl and jq, which can't be found?
Excerpt from my startup log:
```bash
/usr/sbin/start_vernemq: line 28: jq: command not found
/usr/sbin/start_vernemq: line 28: curl: command not found
/usr/sbin/start_vernemq: line 29: [: ==: unary operator expected
/usr/sbin/start_vernemq: line 37: jq: command not found
/usr/sbin/start_vernemq: line 37: curl: command not found
```

If I understand it correctly, the Dockerfile for 1.6.2 on github does not contain the apt install parameters for curl and jq:
https://github.com/vernemq/docker-vernemq/blob/2cd43171c30bf44ca88c53be76b01ebd786d2ae6/Dockerfile#L25-L28

Interestingly enough, the Dockerfile file on Dockerhub DOES cointain the correct parametes for curl & jq:
https://hub.docker.com/r/erlio/docker-vernemq/~/dockerfile/

Is it possible that somehow the tags on Dockerhub got messed up and the thing we are pulling isn't the latest one?

**Comment by zeisi** [comment]
I've just realized, the missing apt argument for curl and jq are fixed in the master branch
https://github.com/vernemq/docker-vernemq/blob/bea60e3af15c2118e4cc27e498fcee50cd6cffd4/Dockerfile#L25-L28
I will try to build the image myself and report back.

**Comment by dergraf** [comment]
This is indeed strange.
The way it is supposed to work at the moment is the following:
`erlio/docker-vernemq:latest` should contain a release that's built from the VerneMQ sources at the 1.6.2 release tag. Not straightforward is that latest won't point to VerneMQ master, it always points to the VerneMQ release tag. So in that sense `latest`means the latest version of the `docker-vernemq` repo and not the latest version of `vernemq`. We're currently moving away fromm dockerhub automatic builds to a Travis based build pipeline, which would allow us to address this request. 

@zeisi what is `vernemq version` gives you in those containers?

**Comment by dergraf** [comment]
@larshesel do you think it would be save to always fetch master (unless a proper version is provided with the build-args)

**Comment by francois-travais** [comment]
The annoying think for me right now is that if I don't want to use the tag `latest`, for a production setup, I cannot rely on the version tags your pushing. Right now the tag 1.6.2 is just broken and fixed in `latest`. One expects to be able to rely on the tagged version.

Moreover the tag 1.6.2 introduced a completely new directory layout which prevents me from upgrading my resources in k8s with persistent volumes. If I want to upgrade from 1.6.1 to 1.6.2 I have to drain and shut down the entire cluster before starting a new one. It's not something one expects when bumping a patch version.

**Comment by dergraf** [comment]
@zeisi the `vernemq_dev` is a library that's used inside VerneMQ and has nothing to do with the build target.

**Comment by dergraf** [comment]
@zeisi pushed https://hub.docker.com/r/erlio/docker-vernemq/builds/bhr2qf3gslqwvmwrp8i9nqp/
