### ISSUE TITLE
Discussion: How to change the official VerneMQ Docker images

### ISSUE THREAD

**Issue by dergraf** [vernemq/docker-vernemq#80]
Goals: We want to support multiple image types like a larger Debian based image and a small stripped-down Alpine based image. Moreover we want to provide Docker Images that use the new SWC replication algorithm out-of-the-box but keep Docker images with the current/stable replication algorithm. We want to do differntiate between those multiple versions with Docker tags.

The easiest way to make this work is to have a Docker image that doesn't use a VerneMQ release that was installed via one of our official packages (today we take the official Debian Jessie package), but uses a pre-build VerneMQ release directly. The main downside of such an approach is that existing Docker volume mounts have to be adjusted to reflect the new directory structure.

The following adjustments would be necessary:

/etc/vernemq --> /vernemq/etc
/var/log/vernemq --> /vernemq/log
/var/lib/vernemq --> /vernemq/data

the changes can be handled in a (sort of) backward compatible way using OS symlinks.

Also the binaries vernemq, vmq-admin, vmq-passwd are inside /vernemq/bin and cannot be easily copied into /usr/sbin.

What do you think about this? Is this a change that could be done right away, or does it need special care for current Docker based deployments?

**Comment by larshesel** [comment]
One (slight) drawback is that we'd then have less users (testers) of the VerneMQ jessie package - but I think we should tackle that problem in general in some other way, just wanted to mention it.

Can't well comment on the consequences for Docker based deployments, know too little about it.

> Also the binaries vernemq, vmq-admin, vmq-passwd are inside /vernemq/bin and cannot be easily copied into /usr/sbin.

Why is that a problem? Wouldn't it be possible to symlink these as well?

**Comment by larshesel** [comment]
I imagine as a developer it would be easier going from commit -> full kubernetes cluster if one could skip having to build an actual package. Faster feedback cycles for experiments are always welcome.

**Comment by dergraf** [comment]
The developer doesn't have to build anything, she just uses the image.

what I propose is that we build images that use a fustom build VerneMQ instead of the prebuild packages.

**Comment by larshesel** [comment]
> The developer

I'm talking about *me* here. ;)
