### ISSUE TITLE
VerneMQ Helm chart

### ISSUE THREAD

**Issue by francois-travais** [vernemq/docker-vernemq#82]
It would be really nice to have an "official" [Helm](https://helm.sh/) chart to deploy VerneMQ on a Kubernetes cluster. It would avoid the issues like #79. I'me pretty sure the VerneMQ dev team already have templates of Kuberntes configurations.

Best would be to have it into the [official Helm chart repository](https://github.com/helm/charts).

**Comment by larshesel** [comment]
We don't have this yet, but would be cool of course, but will also require quite a bit of effort and cost to get done. Contributions welcome!

**Comment by francois-travais** [comment]
@larshesel Now we have something to work on.

**Comment by larshesel** [comment]
This is awesome! Thanks for this - we'll take a look at this soon!
